import time, datetime

import numpy as np

from .core import (pyNMB_location, get_resource_path, timer, RAB, Rbetween2Points,
                   vector, vectorBetween2Points, coord2xyz, vertex, vertexScaled, RadiusSphereAfterV,
                   centerOfGravity, center2cog, normOfV, normV, centerToVertices, Rx, Ry, Rz,
                   EulerRotationMatrix, plotPalette, rgb2hex, clone, deleteElementsOfAList,
                   planeFittingLSF, faces_to_planes, AngleBetweenVV, signedAngleBetweenVV
                   )
from .core import centertxt, centerTitle, fg, bg, hl, color
from .geometry import truncateAbovePlanes, setdAsNegative, rotationMolAroundAxis

import ase
#==================================================================================
#                          Constructive solid geometry
#==================================================================================

def applySlicing(self,
             planes,
             distance_unit: str = 'nm',
             mode: str = 'OR',
             recenter: bool=True,
             noOutput: bool = False,
             postAnalyzis: bool = None,
             skipChiralityCalculation: bool = None,
             skipSymmetryAnalyzis: bool = None,
             skipFacetInfo: bool = None,
             thresholdCoreSurface: float = None,
             ):
    """
    Apply one or more truncation plane groups to self.NP, with optional
    rotational symmetry generation and logical combination of groups.
    Works on any pyNMBcore object.

    Each plane group is defined by a dictionary. Within a group, planes are
    generated by rotational symmetry (nRot) around rotAxis, and combined
    according to the group-level 'modeP' key. Groups are then combined
    according to the top-level 'mode' parameter.

    Plane group keys:

        Plane definition (one of, mandatory):
            'normal' (array-like): Plane normal as a Cartesian vector [u, v, w]
                (if normal_def='cart', default) or Miller indices [h, k, l]
                (if normal_def='hkl', requires self.Gstar — Crystal objects only).
            'angle' (float): Angle in degrees between the plane normal and
                rotAxis. The reference normal is built from a starting
                direction (see 'startVec') rotated by this angle around rotAxis.

        Mandatory keys:
            'distance' (float): Signed orthogonal distance from the origin
                (center of mass of the NP) to the truncation plane, in nm
                (default) or Å (distance_unit), along the plane normal n.
                The plane is defined by n · x = distance, where x is any
                point on the plane.
                - distance > 0 : plane is on the positive side of n,
                                 at distance Å from the origin.
                - distance = 0 : plane passes through the origin.
                - distance < 0 : plane is on the negative side of n,
                                 at |distance| Å from the origin.
            'delete' (str): Which atoms to remove.
                'above' removes atoms on the positive side of the plane normal.
                'below' removes atoms on the negative side.
                Default is 'above'.

        Optional keys:
            'normal_def' (str): Coordinate system for 'normal'. Either 'cart'
                (Cartesian, default) or 'hkl' (Miller indices, Crystal only).
            'nRot' (int): Number of planes generated by rotation around rotAxis.
                Rotation angle = 360° / nRot. Default is 1 (no rotation).
            'rotAxis' (array-like): Rotation axis as a Cartesian vector.
                Required if nRot > 1.
            'startVec' (array-like, optional): Starting direction used to build
                the reference normal in 'angle' mode. Only its component
                perpendicular to rotAxis is used, so it need not be orthogonal
                to rotAxis — but it must not be collinear with it. If omitted,
                an arbitrary perpendicular direction is chosen.
            'startAngle' (float, optional): Azimuth in degrees, around rotAxis,
                of the in-plane reference direction, measured from 'refVec'.
                Mutually exclusive with 'startVec' (error if both are given).
            'refVec' (array-like, optional): Direction defining the 0° azimuth
                for 'startAngle'. Only its component perpendicular to rotAxis is
                used; must not be collinear with rotAxis. Only valid together
                with 'startAngle'. Defaults to an arbitrary perpendicular.
            'modeP' (str): Logical combination of planes within this group.
                'OR'  — atom removed if condemned by ANY plane in the group.
                        Default when side='above'. Use for faceting.
                'AND' — atom removed only if condemned by ALL planes in the group
                        simultaneously. Default when side='below'.
                        Use for concave holes or pyramidal cavities.

    Args:
        planes (list of dict): List of plane group definitions (see above).
        distance_unit (str): Unit for all distances. 'nm' (default) or
            'Angstrom'.
        mode (str): Logical combination of plane groups.
            'OR'  — atom removed if condemned by ANY group (default).
                    Use for standard faceting or combined truncations.
            'AND' — atom removed only if condemned by ALL groups simultaneously.
                    Use for complex intersections.
        recenter (bool): If True, recenters self.NP on its center of mass
            after slicing (default). Set to False when calling applySlicing
            multiple times in sequence (e.g. applying the same pattern on
            all 6 faces of a cube) to avoid shifting the reference frame
            between calls. In that case, recenter manually once at the end:
            NP.NP.positions -= NP.NP.get_center_of_mass()
        noOutput (bool): If True, suppresses all printed output.
            Default is False.
        postAnalyzis (bool): If True, prints additional NP information.
        skipChiralityCalculation (bool): If True, skips the calculation of
            the OPD (Osipov-Pickup-Dunmur) chirality index.
        skipSymmetryAnalyzis (bool): If True, skips the symmetry analysis.
        skipFacetInfo (bool): If True, skips the external-facet info calculation.
        thresholdCoreSurface (float): Threshold used to distinguish core from
            surface atoms.
            
    Note:
        Updates self.NP, self.nAtoms and self.cog in place.
        self.trPlanes_Slices is updated with all applied truncation planes.
        self.trPlanes_Wulff is set to None (not a Wulff construction).
        A recentering on the center of mass is applied after all truncations.
        If the operation would delete all atoms, it is cancelled and a
        detailed summary of each group is printed to help diagnose the issue.

    Examples:
        # Facet a cube with 4 {010} planes (OR mode, default)
        NP.applySlicing(
            planes=[
                {'normal': [0, 1, 0], 'distance': 6.0,
                 'nRot': 4, 'rotAxis': [0, 0, 1], 'delete': 'above'},
            ],
            distance_unit='Angstrom'
        )

        # Carve a pyramidal hole on top of a cube
        NP.applySlicing(
            planes=[
                {'normal': [0, 1, 1], 'distance': 5.0,
                 'nRot': 4, 'rotAxis': [0, 0, 1],
                 'delete': 'below', 'modeP': 'AND'},
            ],
            distance_unit='Angstrom'
        )

        # Facet AND cut a top slice simultaneously (AND between groups)
        NP.applySlicing(
            planes=[
                {'normal': [0, 1, 0], 'distance': 6.0,
                 'nRot': 4, 'rotAxis': [0, 0, 1], 'delete': 'above'},
                {'normal': [0, 0, 1], 'distance': 6.0,
                 'nRot': 1, 'delete': 'above'},
            ],
            mode='AND',
            distance_unit='Angstrom'
        )
    """
    if not noOutput:
        centertxt(f"Slicing operation (mode={mode})", bgc="#cbcbcb", size="12",
                  fgc="b", weight="bold")

    if mode not in ('OR', 'AND'):
        print(f"{bg.LIGHTYELLOWB}Warning: unknown mode '{mode}', "
              f"defaulting to 'OR'.{bg.OFF}")
        mode = 'OR'

    # --- Unit conversion ---
    scale = 10.0 if distance_unit == 'nm' else 1.0  # nm → Å

    all_tr_planes = []
    group_masks   = []
    group_summaries = []   # for error reporting

    for plane_def in planes:

        # --- Side to delete --- backward compatibility with 'side'
        if 'side' in plane_def and 'delete' not in plane_def:
            delete = plane_def['side']  # legacy alias
        else:
            delete = plane_def.get('delete', 'above')
            
        # --- Distance ---
        distance_ang = plane_def['distance'] * scale

        # --- Side 2 delete---
        delete = plane_def.get('delete', 'above')
        if delete not in ('above', 'below'):
            print(f"{bg.LIGHTYELLOWB}Warning: unknown side to delete '{delete}', "
                  f"defaulting to 'above'.{bg.OFF}")
            delete = 'above'
        del_above = (delete == 'above')

        # --- modeP within group ---
        default_modeP = 'AND' if delete == 'below' else 'OR'
        modeP = plane_def.get('modeP', default_modeP)
        if modeP not in ('OR', 'AND'):
            print(f"{bg.LIGHTYELLOWB}Warning: unknown modeP '{modeP}', "
                  f"defaulting to '{default_modeP}'.{bg.OFF}")
            modeP = default_modeP
        allP_group = (modeP == 'AND')

        # --- Build reference normal in Cartesian ---
        if 'normal' in plane_def:
            normal_def = plane_def.get('normal_def', 'cart')
            n = np.array(plane_def['normal'], dtype=float)
            if normal_def == 'hkl':
                if not hasattr(self, 'Gstar'):
                    raise AttributeError(
                        "normal_def='hkl' requires a Crystal object with "
                        "self.Gstar. Use normal_def='cart' instead.")
                from .crystals import lattice_cart
                n = lattice_cart(self, [n], Bravais2cart=True)[0]
            n = n / np.linalg.norm(n)

        elif 'angle' in plane_def:
            rot_axis = np.array(plane_def['rotAxis'], dtype=float)
            rot_axis = rot_axis / np.linalg.norm(rot_axis)
            angle_deg = plane_def['angle']

            def _project_perp(vec, name):
                """Component of `vec` perpendicular to rot_axis, normalized."""
                v = np.array(vec, dtype=float)
                if np.linalg.norm(v) < 1e-12:
                    raise ValueError(f"'{name}' must be a non-zero vector.")
                v = v / np.linalg.norm(v)
                p = v - np.dot(v, rot_axis) * rot_axis
                if np.linalg.norm(p) < 1e-8:
                    raise ValueError(
                        f"'{name}' is collinear with 'rotAxis'; it has no "
                        f"component in the plane perpendicular to the axis.")
                return p / np.linalg.norm(p)

            # In-plane reference direction (the "meridian"), defined by ONE of:
            #   - 'startVec'  : given directly as a vector
            #   - 'startAngle': azimuth (deg) around rotAxis from 'refVec'
            #                   (refVec defaults to an arbitrary perpendicular)
            #   - neither     : arbitrary perpendicular (previous default)
            if 'startVec' in plane_def and 'startAngle' in plane_def:
                raise ValueError(
                    "Provide either 'startVec' or 'startAngle', not both.")

            if 'startVec' in plane_def:
                perp = _project_perp(plane_def['startVec'], 'startVec')
            elif 'startAngle' in plane_def:
                if 'refVec' in plane_def:
                    ref = _project_perp(plane_def['refVec'], 'refVec')
                else:
                    arbitrary = np.array([1, 0, 0]) if abs(rot_axis[0]) < 0.9 \
                                else np.array([0, 1, 0])
                    ref = np.cross(rot_axis, arbitrary)
                    ref = ref / np.linalg.norm(ref)
                perp = rotationMolAroundAxis(ref, plane_def['startAngle'], rot_axis)
                perp = perp / np.linalg.norm(perp)
            else:
                if 'refVec' in plane_def:
                    raise ValueError(
                        "'refVec' is only meaningful together with "
                        "'startAngle'.")
                arbitrary = np.array([1, 0, 0]) if abs(rot_axis[0]) < 0.9 \
                            else np.array([0, 1, 0])
                perp = np.cross(rot_axis, arbitrary)
                perp = perp / np.linalg.norm(perp)

            # Tilt the meridian towards +rotAxis by 'angle' (0° = radial).
            tilt_axis = np.cross(perp, rot_axis)
            tilt_axis = tilt_axis / np.linalg.norm(tilt_axis)
            n = rotationMolAroundAxis(perp, angle_deg, tilt_axis)
            n = n / np.linalg.norm(n)
        else:
            raise ValueError(
                "Each plane definition must contain either 'normal' or 'angle'.")

        # --- Generate rotational family ---
        nRot = plane_def.get('nRot', 1)
        if nRot < 1:
            print(f"{bg.LIGHTYELLOWB}Warning: nRot={nRot} is invalid, "
                  f"set to 1.{bg.OFF}")
            nRot = 1

        if nRot > 1:
            rot_axis = np.array(plane_def['rotAxis'], dtype=float)
            rot_axis = rot_axis / np.linalg.norm(rot_axis)
            normals = [rotationMolAroundAxis(n, i * 360.0 / nRot, rot_axis)
                       for i in range(nRot)]
        else:
            normals = [n]

        # --- Build plane equations [nx, ny, nz, d] with d < 0 ---
        family_planes = []
        for nn in normals:
            nn = nn / np.linalg.norm(nn)
            plane_eq = np.append(nn, -distance_ang)
            all_tr_planes.append(plane_eq)
            family_planes.append(plane_eq)
        family_planes = np.array(family_planes)

        if not noOutput:
            normal_label = plane_def.get('normal', None)
            if normal_label is None:
                normal_label = f"angle={plane_def.get('angle')}"
            print(f"\n  Group {len(group_masks)+1} — "
                  f"normal: {normal_label}"
                  f"  nRot: {nRot}  distance: {plane_def['distance']} {distance_unit}"
                  f"  side to delete: {delete}  modeP: {modeP}")
            for nn in normals:
                nn_n = nn / np.linalg.norm(nn)
                print(f"    [{nn_n[0]:+.4f} {nn_n[1]:+.4f} {nn_n[2]:+.4f}]"
                      f"  d = {distance_ang:.3f} Å")

        # --- Compute group mask ---
        group_mask = truncateAbovePlanes(
            family_planes,
            self.NP.positions,
            allP=allP_group,
            delAbove=del_above,
            eps=getattr(self, 'threshold', 1e-3),
            debug=False,
            noOutput=True,
        )
        group_masks.append(group_mask)
        group_summaries.append({
            'normal': plane_def.get('normal', f"angle={plane_def.get('angle')}"),
            'distance': plane_def['distance'],
            'delete': delete,
            'modeP': modeP,
            'nRot': nRot,
            'n_condemned': int(np.count_nonzero(group_mask)),
        })

    # --- Combine group masks according to mode ---
    if len(group_masks) == 0:
        if not noOutput:
            print("No planes defined — nothing to do.")
        return

    if mode == 'OR':
        final_mask = group_masks[0]
        for m in group_masks[1:]:
            final_mask = final_mask | m
    else:  # 'AND'
        final_mask = group_masks[0]
        for m in group_masks[1:]:
            final_mask = final_mask & m

    # --- Safety check: would all atoms be deleted? ---
    n_total  = len(self.NP)
    n_to_del = int(np.count_nonzero(final_mask))

    if n_to_del == n_total:
        print(f"\n{bg.DARKREDB}ERROR: all {n_total} atoms would be deleted! "
              f"Operation cancelled.{bg.OFF}")
        print(f"\n{bg.LIGHTYELLOWB}Summary of plane groups:{bg.OFF}")
        print(f"  Global mode : {mode}")
        print(f"  {'Group':<6} {'normal':<20} {'distance':>10} "
              f"{'delete':<8} {'modeP':<6} {'nRot':<6} {'condemned':>10}")
        print(f"  {'─'*70}")
        for i, s in enumerate(group_summaries):
            print(f"  {i+1:<6} {str(s['normal']):<20} "
                  f"{s['distance']:>8.3f} {distance_unit}  "
                  f"{s['delete']:<8} {s['modeP']:<6} {s['nRot']:<6} "
                  f"{s['n_condemned']:>6}/{n_total}")
        print(f"\n{bg.LIGHTYELLOWB}Hints:{bg.OFF}")
        print(f"  - Check distances (too small → plane inside NP → everything condemned)")
        print(f"  - Check delete ('above' vs 'below')")
        print(f"  - Check modeP ('OR' vs 'AND') within each group")
        print(f"  - Check mode ('OR' vs 'AND') between groups")
        return

    # --- Apply final mask ---
    self.NP = self.NP[~final_mask]

    group_info = []
    delete_by_plane = []
    for i, plane_def in enumerate(planes):
        nRot = plane_def.get('nRot', 1)
        if 'side' in plane_def and 'delete' not in plane_def:
            d = plane_def['side']  # backward compatibility
        else:
            d = plane_def.get('delete', 'above')
        for _ in range(nRot):
            group_info.append(i)
            delete_by_plane.append(d)
    
    self.trPlanes_Slicing_groups = group_info
    self.trPlanes_Slicing_delete = delete_by_plane

    # --- Recenter ---
    if recenter:
        com_shift = self.NP.get_center_of_mass()  # ← avant le recentrage !
        self.NP.positions -= com_shift
        # Update plane distances to account for recentering
        if len(all_tr_planes) > 0:
            all_tr_planes_arr = np.array(all_tr_planes)
            for i, plane in enumerate(all_tr_planes_arr):
                n = plane[:3]
                # New d = old d + n · shift
                all_tr_planes_arr[i, 3] += np.dot(n, com_shift)
            all_tr_planes = all_tr_planes_arr.tolist()

    # --- Update attributes ---
    self.trPlanes_Slices  = setdAsNegative(np.array(all_tr_planes))
    self.trPlanes_Wulff   = None
    self.nAtoms           = len(self.NP)
    self.cog              = self.NP.get_center_of_mass()
    self._flush_stale_data(shape_update="_Slices")
    self.is_optimized     = False
    
    if not noOutput:
        print(f"  {n_to_del} atoms removed, {self.nAtoms} remaining.")
        
    # --- Resolve parameters ---
    if postAnalyzis is None:
        postAnalyzis = getattr(self, 'postAnalyzis', True)
    if skipChiralityCalculation is None:
        skipChiralityCalculation = getattr(self, 'skipChiralityCalculation', True)
    if skipSymmetryAnalyzis is None:
        skipSymmetryAnalyzis = getattr(self, 'skipSymmetryAnalyzis', True)
    if skipFacetInfo is None:
        skipFacetInfo = getattr(self, 'skipFacetInfo', True)
    if thresholdCoreSurface is None:
        thresholdCoreSurface = getattr(self, 'thresholdCoreSurface', 3.0)

    if postAnalyzis:
        self.propPostMake(
            skipChiralityCalculation = skipChiralityCalculation,
            skipSymmetryAnalyzis     = skipSymmetryAnalyzis,
            skipFacetInfo            = skipFacetInfo,
            thresholdCoreSurface     = thresholdCoreSurface,
            noOutput                 = noOutput,
            is_optimized             = False,
        )

def _apply_rotB(pos_B, rotB):
    """
    Apply one or more rotations to positions pos_B.
    rotB can be:
      - None                          : no rotation
      - [ux, uy, uz, angle]           : single rotation, axis + angle in degrees
      - {'axis': [...], 'angle': ...} : single rotation as dict
      - [{'axis': [...], 'angle': ...}, ...] : list of rotations applied in order
    """
    if rotB is None:
        return pos_B

    # Normalize to a list of dicts
    if isinstance(rotB, (list, np.ndarray)) and len(rotB) == 4 and not isinstance(rotB[0], dict):
        # [ux, uy, uz, angle] shorthand
        rotations = [{'axis': list(rotB[:3]), 'angle': float(rotB[3])}]
    elif isinstance(rotB, dict):
        rotations = [rotB]
    elif isinstance(rotB, list) and isinstance(rotB[0], dict):
        rotations = rotB
    else:
        raise ValueError(
            "rotB must be [ux, uy, uz, angle], a dict {'axis':..., 'angle':...}, "
            "or a list of such dicts.")

    # Apply rotations in order
    for rot in rotations:
        axis  = np.array(rot['axis'], dtype=float)
        angle = float(rot['angle'])
        axis  = axis / np.linalg.norm(axis)
        pos_B = rotationMolAroundAxis(pos_B, angle, axis)

    return pos_B
    
def cut_by(self,
            NP_B,
            cogB: list = None,
            rotB=None,
            mode: str = 'hull',
            threshold: float = 0.8,
            recenter: bool=True,
            noOutput: bool = False,
            postAnalyzis: bool = None,
            skipChiralityCalculation: bool = None,
            skipSymmetryAnalyzis: bool = None,
            skipFacetInfo: bool = None,
            thresholdCoreSurface: float = None,
             ):
    """
    Remove from self.NP (object A) the atoms that lie inside object B,
    creating a hollow cavity in the shape of B.

    Two modes are available:
    - 'hull' : atoms of A inside the convex hull of B are removed.
               Fast and geometrically exact for convex shapes.
    - 'atoms': atoms of A closer than threshold * Rnn to any atom of B
               are removed. Works for any shape, respects the atomic lattice.

    Args:
        self: pyNMBcore object (A). Modified in place.
        NP_B: pyNMBcore object (B). Defines the cavity shape.
        cogB (list): Position in nm where the center of mass of B is placed
            before the operation. Default is None (B used as-is).
        rotB: Rotation applied to B before the operation, around its own
            center of mass. Accepts three forms:
            - None (default): no rotation.
            - [ux, uy, uz, angle]: single rotation — axis [ux, uy, uz]
              (Cartesian) and angle in degrees.
              Example: [0, 0, 1, 45.0] rotates B by 45° around z.
            - {'axis': [ux, uy, uz], 'angle': angle}: same as above,
              as a dictionary.
            - [{'axis': [...], 'angle': ...}, ...]: list of rotations
              applied sequentially in the given order.
              Example: [{'axis': [0,0,1], 'angle': 45.0},
                        {'axis': [1,0,0], 'angle': 30.0}]
              rotates B first by 45° around z, then by 30° around x.
        mode (str): 'hull' (default) or 'atoms'.
        threshold (float): Only for mode='atoms'. Atoms of A closer than
            threshold * Rnn_A to any atom of B are removed. Default is 0.8.
        recenter (bool): If True, recenters self.NP on its center of mass
            after slicing (default). Set to False when calling applySlicing
            multiple times in sequence (e.g. applying the same pattern on
            all 6 faces of a cube) to avoid shifting the reference frame
            between calls. In that case, recenter manually once at the end:
            NP.NP.positions -= NP.NP.get_center_of_mass()
        noOutput (bool): If True, suppresses output. Default is False.
        postAnalyzis (bool): If True, prints additional NP information.
        skipChiralityCalculation (bool): If True, skips the calculation of
            the OPD (Osipov-Pickup-Dunmur) chirality index.
        skipSymmetryAnalyzis (bool): If True, skips the symmetry analysis.
        skipFacetInfo (bool): If True, skips the external-facet info calculation.
        thresholdCoreSurface (float): Threshold used to distinguish core from
            surface atoms.

    Note:
        Updates self.NP, self.nAtoms and self.cog in place.
        Does not modify NP_B.

    Example:
        # Create a spherical hollow in a gold cube
        AuCube  = pNP.cube(element='Au', ...)
        PtSphere = Crystal('Pt fcc', shape='sphere', size=[2])
        AuCube.minus(PtSphere, cogB=[0, 0, 0], mode='hull')
    """
    if not noOutput:
        centertxt(f"CSG minus (mode={mode})", bgc="#cbcbcb", size="12",
                  fgc="b", weight="bold")

    if mode not in ('hull', 'atoms'):
        print(f"{bg.LIGHTYELLOWB}Warning: unknown mode '{mode}', "
              f"defaulting to 'hull'.{bg.OFF}")
        mode = 'hull'

    # --- Position B at cogB ---
    pos_B = NP_B.NP.get_positions().copy()
    cog_B = NP_B.NP.get_center_of_mass()
    # --- Rotate B around its own center of mass, then translate ---
    pos_B = pos_B - cog_B          # center B at origin before rotation
    pos_B = _apply_rotB(pos_B, rotB)  # rotate
    if cogB is not None:
        cogB_ang = np.array(cogB) * 10.0  # nm → Å
        pos_B = pos_B - cog_B + cogB_ang  # shift B to cogB

    # --- Positions of A ---
    pos_A = self.NP.get_positions()
    n_total = len(pos_A)

    # --- Compute mask: atoms of A to remove ---
    # --- Estimate Rnn_A --- needed for both modes
    Rnn_A = getattr(self, 'Rnn', None)
    if Rnn_A is None:
        from scipy.spatial import KDTree
        tree = KDTree(pos_A)
        dists, _ = tree.query(pos_A, k=2)
        Rnn_A = np.median(dists[:, 1])
        if not noOutput:
            print(f"  Rnn_A estimated: {Rnn_A:.3f} Å")
    cutoff = threshold * Rnn_A

    if mode == 'hull':
        from scipy.spatial import ConvexHull, Delaunay, KDTree
        # Compute hull on surface atoms of B if available
        if hasattr(NP_B, 'surfaceAtoms') and NP_B.surfaceAtoms is not None:
            pos_B_hull = pos_B[NP_B.surfaceAtoms]
        else:
            pos_B_hull = pos_B
        hull_B = ConvexHull(pos_B_hull)
        delaunay_B = Delaunay(pos_B_hull[hull_B.vertices])
        # Atoms strictly inside hull
        inside_hull = delaunay_B.find_simplex(pos_A) >= 0
        # Also remove atoms within cutoff of any surface atom of B
        tree_surf = KDTree(pos_B_hull)
        dists_to_surf, _ = tree_surf.query(pos_A)
        near_surface = dists_to_surf < cutoff
        inside_mask = inside_hull | near_surface
    else:  # mode == 'atoms'
        from scipy.spatial import KDTree
        Rnn_A = getattr(self, 'Rnn', None)
        if Rnn_A is None:
            # Estimate Rnn from nearest neighbor distances
            tree = KDTree(pos_A)
            dists, _ = tree.query(pos_A, k=2)
            Rnn_A = np.median(dists[:, 1])
            if not noOutput:
                print(f"  Rnn_A estimated: {Rnn_A:.3f} Å")
        cutoff = threshold * Rnn_A
        tree_B = KDTree(pos_B)
        dists, _ = tree_B.query(pos_A)
        inside_mask = dists < cutoff

    # --- Safety check ---
    n_to_del = int(np.count_nonzero(inside_mask))
    if n_to_del == n_total:
        print(f"\n{bg.DARKREDB}ERROR: all {n_total} atoms of A would be "
              f"deleted! Operation cancelled.{bg.OFF}")
        print(f"  Check cogB position and mode='{mode}'.")
        return

    if n_to_del == 0:
        print(f"{bg.LIGHTYELLOWB}Warning: no atoms removed — "
              f"B may not overlap with A. Check cogB position.{bg.OFF}")
        return

    # --- Apply mask ---
    self.NP = self.NP[~inside_mask]

    # --- Remove isolated/undercoordinated atoms after cut ---
    # Atoms left floating after the cut (e.g. at cavity edges) are removed
    from .geometry import peel_by_coordination
    n_before = len(self.NP)
    peel_by_coordination(self,
                         threshold_peeling=1,  # remove only truly isolated atoms
                         Rmax=1.2 * Rnn_A,
                         postAnalyzis=False,
                         noOutput=True)
    n_removed_isolated = n_before - len(self.NP)
    if not noOutput and n_removed_isolated > 0:
        print(f"{bg.LIGHTYELLOWB}Warning: {n_removed_isolated} isolated "
              f"atom(s) removed after cut.{bg.OFF}")
        
    # --- Invalidate old truncation planes ---
    # After intersection, the original planes are no longer valid
    # since the shape has fundamentally changed
    self.trPlanes      = None
    self.trPlanes_Wulff = None
    self.trPlanes_opt   = None
    # --- Recenter at origin ---
    if recenter:
        self.NP.positions -= self.NP.get_center_of_mass()

    # --- Update attributes ---
    self.nAtoms = len(self.NP)
    self.cog    = self.NP.get_center_of_mass()
    self._flush_stale_data(shape_update="_hollow")
    self.is_optimized = False

    if not noOutput:
        print(f"  {n_to_del} atoms removed from A, "
              f"{self.nAtoms} remaining.")

    # --- Resolve parameters ---
    if postAnalyzis is None:
        postAnalyzis = getattr(self, 'postAnalyzis', True)
    if skipChiralityCalculation is None:
        skipChiralityCalculation = getattr(self, 'skipChiralityCalculation', True)
    if skipSymmetryAnalyzis is None:
        skipSymmetryAnalyzis = getattr(self, 'skipSymmetryAnalyzis', True)
    if skipFacetInfo is None:
        skipFacetInfo = getattr(self, 'skipFacetInfo', True)
    if thresholdCoreSurface is None:
        thresholdCoreSurface = getattr(self, 'thresholdCoreSurface', 3.0)

    if postAnalyzis:
        self.propPostMake(
            skipChiralityCalculation = skipChiralityCalculation,
            skipSymmetryAnalyzis     = skipSymmetryAnalyzis,
            skipFacetInfo            = skipFacetInfo,
            thresholdCoreSurface     = thresholdCoreSurface,
            noOutput                 = noOutput,
            is_optimized             = False,
        )

def union_with(self,
                NP_B,
                cogB: list = None,
                rotB=None,
                mode: str = 'hull',
                threshold: float = 0.8,
                recenter: bool=True,
                noOutput: bool = False,
                postAnalyzis: bool = None,
                skipChiralityCalculation: bool = None,
                skipSymmetryAnalyzis: bool = None,
                skipFacetInfo: bool = None,
                thresholdCoreSurface: float = None,
             ):
    """
    Add NP_B to self.NP (object A), removing overlapping atoms closer
    than threshold * Rnn to avoid unphysical interatomic distances.

    The atoms of B are placed at cogB, optionally rotated by rotB, then
    merged with A. Atoms of A closer than threshold * Rnn to any atom of B
    are removed before merging to avoid overlap.

    Args:
        self: pyNMBcore object (A). Modified in place.
        NP_B: pyNMBcore object (B). Added to A.
        cogB (list): Position in nm where the center of mass of B is placed
            before the operation. Default is None (B used as-is).
        rotB: Rotation applied to B before the operation, around its own
            center of mass. Accepts three forms:
            - None (default): no rotation.
            - [ux, uy, uz, angle]: single rotation — axis [ux, uy, uz]
              (Cartesian) and angle in degrees.
            - {'axis': [ux, uy, uz], 'angle': angle}: same as above.
            - [{'axis': [...], 'angle': ...}, ...]: list of rotations
              applied sequentially in the given order.
        mode (str): 'hull' (default) or 'atoms'.
        threshold (float): Atoms of A closer than threshold * Rnn_A to any
            atom of B are removed before merging. Default is 0.8.
        recenter (bool): If True, recenters self.NP on its center of mass
            after slicing (default). Set to False when calling applySlicing
            multiple times in sequence (e.g. applying the same pattern on
            all 6 faces of a cube) to avoid shifting the reference frame
            between calls. In that case, recenter manually once at the end:
            NP.NP.positions -= NP.NP.get_center_of_mass()
        noOutput (bool): If True, suppresses output. Default is False.
        postAnalyzis (bool): If True, prints additional NP information.
        skipChiralityCalculation (bool): If True, skips the calculation of
            the OPD (Osipov-Pickup-Dunmur) chirality index.
        skipSymmetryAnalyzis (bool): If True, skips the symmetry analysis.
        skipFacetInfo (bool): If True, skips the external-facet info calculation.
        thresholdCoreSurface (float): Threshold used to distinguish core from
            surface atoms.

    Note:
        Updates self.NP, self.nAtoms and self.cog in place.
        Does not modify NP_B.
        The chemical species of B atoms are preserved in the merged structure.

    Example:
        # Insert a Pt octahedron into a hollow Au cube
        AuCube.minus(PtOh, cogB=[0, 0, 0], mode='atoms', threshold=0.8)
        AuCube.plus(PtOh,  cogB=[0, 0, 0], threshold=0.8)
    """
    if not noOutput:
        centertxt("CSG plus", bgc="#cbcbcb", size="12",
                  fgc="b", weight="bold")

    # --- Position and rotate B ---
    pos_B = NP_B.NP.get_positions().copy()
    cog_B = NP_B.NP.get_center_of_mass()
    pos_B = pos_B - cog_B              # center B at origin
    pos_B = _apply_rotB(pos_B, rotB)   # rotate around its own center
    if cogB is not None:
        cogB_ang = np.array(cogB) * 10.0  # nm → Å
        pos_B = pos_B + cogB_ang

    # --- Estimate Rnn_A ---
    pos_A = self.NP.get_positions()
    Rnn_A = getattr(self, 'Rnn', None)
    if Rnn_A is None:
        from scipy.spatial import KDTree
        tree = KDTree(pos_A)
        dists, _ = tree.query(pos_A, k=2)
        Rnn_A = np.median(dists[:, 1])
        if not noOutput:
            print(f"  Rnn_A estimated: {Rnn_A:.3f} Å")

    cutoff = threshold * Rnn_A

    # --- Remove atoms of A that overlap with B ---
    if mode == 'hull':
        from scipy.spatial import ConvexHull, Delaunay, KDTree

        # Compute hull only on surface atoms of B if available
        # — much faster than using all atoms
        if hasattr(NP_B, 'surfaceAtoms') and NP_B.surfaceAtoms is not None:
            pos_B_hull = pos_B[NP_B.surfaceAtoms]
        else:
            pos_B_hull = pos_B

        hull_B = ConvexHull(pos_B_hull)
        delaunay_B = Delaunay(pos_B_hull[hull_B.vertices])

        # Atoms strictly inside hull
        inside_hull = delaunay_B.find_simplex(pos_A) >= 0

        # Also remove atoms of A within cutoff of ANY surface atom of B
        # — hull vertices alone are not enough (only corners, missing most surface)
        if hasattr(NP_B, 'surfaceAtoms') and NP_B.surfaceAtoms is not None:
            pos_B_surface = pos_B[NP_B.surfaceAtoms]
        else:
            pos_B_surface = pos_B
        tree_surf = KDTree(pos_B_surface)
        dists_to_surf, _ = tree_surf.query(pos_A)
        near_surface = dists_to_surf < cutoff
        overlap_mask = inside_hull | near_surface

    else:  # mode == 'atoms'
        from scipy.spatial import KDTree
        tree_B = KDTree(pos_B)
        dists_A, _ = tree_B.query(pos_A)
        overlap_mask = dists_A < cutoff
        
    n_removed = int(np.count_nonzero(overlap_mask))
    if not noOutput:
        print(f"  {n_removed} atoms of A removed (overlap within "
              f"{threshold:.2f} * Rnn = {cutoff:.3f} Å)")

    self.NP = self.NP[~overlap_mask]

    # --- Build merged ASE Atoms object ---
    NP_B_shifted = NP_B.NP.copy()
    NP_B_shifted.set_positions(pos_B)

    merged = self.NP + NP_B_shifted

    # --- Update attributes ---
    self.NP     = merged
    self.nAtoms = len(self.NP)

    # --- Invalidate old truncation planes ---
    # After intersection, the original planes are no longer valid
    # since the shape has fundamentally changed
    self.trPlanes      = None
    self.trPlanes_Wulff = None
    self.trPlanes_opt   = None
    # --- Recenter at origin ---
    if recenter: 
        self.NP.positions -= self.NP.get_center_of_mass()
    
    self.cog    = self.NP.get_center_of_mass()
    self._flush_stale_data(shape_update="_plus")
    self.is_optimized = False

    if not noOutput:
        print(f"  {len(NP_B_shifted)} atoms of B added, "
              f"{self.nAtoms} total atoms.")

    # --- Resolve parameters ---
    if postAnalyzis is None:
        postAnalyzis = getattr(self, 'postAnalyzis', True)
    if skipChiralityCalculation is None:
        skipChiralityCalculation = getattr(self, 'skipChiralityCalculation', True)
    if skipSymmetryAnalyzis is None:
        skipSymmetryAnalyzis = getattr(self, 'skipSymmetryAnalyzis', True)
    if skipFacetInfo is None:
        skipFacetInfo = getattr(self, 'skipFacetInfo', True)
    if thresholdCoreSurface is None:
        thresholdCoreSurface = getattr(self, 'thresholdCoreSurface', 3.0)

    if postAnalyzis:
        self.propPostMake(
            skipChiralityCalculation = skipChiralityCalculation,
            skipSymmetryAnalyzis     = skipSymmetryAnalyzis,
            skipFacetInfo            = skipFacetInfo,
            thresholdCoreSurface     = thresholdCoreSurface,
            noOutput                 = noOutput,
            is_optimized             = False,
        )

def intersect_with(self,
                    NP_B,
                    cogB: list = None,
                    rotB=None,
                    mode: str = 'hull',
                    threshold: float = 0.8,
                    recenter: bool=True,
                    noOutput: bool = False,
                    postAnalyzis: bool = None,
                    skipChiralityCalculation: bool = None,
                    skipSymmetryAnalyzis: bool = None,
                    skipFacetInfo: bool = None,
                    thresholdCoreSurface: float = None,
             ):
    """
    Keep in self.NP (object A) only the atoms that lie inside object B,
    discarding everything outside.

    Two modes are available:
    - 'hull' : only atoms of A inside the convex hull of B are kept.
               Fast and geometrically exact for convex shapes.
    - 'atoms': only atoms of A closer than threshold * Rnn to any atom
               of B are kept. Works for any shape.

    Args:
        self: pyNMBcore object (A). Modified in place.
        NP_B: pyNMBcore object (B). Defines the intersection region.
        cogB (list): Position in nm where the center of mass of B is placed
            before the operation. Default is None (B used as-is).
        rotB: Rotation applied to B before the operation, around its own
            center of mass. Accepts three forms:
            - None (default): no rotation.
            - [ux, uy, uz, angle]: single rotation — axis [ux, uy, uz]
              (Cartesian) and angle in degrees.
            - {'axis': [ux, uy, uz], 'angle': angle}: same as above.
            - [{'axis': [...], 'angle': ...}, ...]: list of rotations
              applied sequentially in the given order.
        mode (str): 'hull' (default) or 'atoms'.
        threshold (float): Only for mode='atoms'. Atoms of A closer than
            threshold * Rnn_A to any atom of B are kept. Default is 0.8.
        recenter (bool): If True, recenters self.NP on its center of mass
            after slicing (default). Set to False when calling applySlicing
            multiple times in sequence (e.g. applying the same pattern on
            all 6 faces of a cube) to avoid shifting the reference frame
            between calls. In that case, recenter manually once at the end:
            NP.NP.positions -= NP.NP.get_center_of_mass()
        noOutput (bool): If True, suppresses output. Default is False.
        postAnalyzis (bool): If True, prints additional NP information.
        skipChiralityCalculation (bool): If True, skips the calculation of
            the OPD (Osipov-Pickup-Dunmur) chirality index.
        skipSymmetryAnalyzis (bool): If True, skips the symmetry analysis.
        skipFacetInfo (bool): If True, skips the external-facet info calculation.
        thresholdCoreSurface (float): Threshold used to distinguish core from
            surface atoms.

    Note:
        Updates self.NP, self.nAtoms and self.cog in place.
        Does not modify NP_B.

    Example:
        # Keep only the part of a cube that overlaps with a sphere
        AuCube.intersect(PtSphere, cogB=[0, 0, 0], mode='hull')
    """
    if not noOutput:
        centertxt(f"CSG intersect (mode={mode})", bgc="#cbcbcb", size="12",
                  fgc="b", weight="bold")

    if mode not in ('hull', 'atoms'):
        print(f"{bg.LIGHTYELLOWB}Warning: unknown mode '{mode}', "
              f"defaulting to 'hull'.{bg.OFF}")
        mode = 'hull'

    # --- Position and rotate B ---
    pos_B = NP_B.NP.get_positions().copy()
    cog_B = NP_B.NP.get_center_of_mass()
    pos_B = pos_B - cog_B              # center B at origin
    pos_B = _apply_rotB(pos_B, rotB)   # rotate around its own center
    if cogB is not None:
        cogB_ang = np.array(cogB) * 10.0  # nm → Å
        pos_B = pos_B + cogB_ang

    # --- Positions of A ---
    pos_A = self.NP.get_positions()
    n_total = len(pos_A)

    # --- Estimate Rnn_A ---
    Rnn_A = getattr(self, 'Rnn', None)
    if Rnn_A is None:
        from scipy.spatial import KDTree
        tree = KDTree(pos_A)
        dists, _ = tree.query(pos_A, k=2)
        Rnn_A = np.median(dists[:, 1])
        if not noOutput:
            print(f"  Rnn_A estimated: {Rnn_A:.3f} Å")
    cutoff = threshold * Rnn_A

    # --- Compute mask: atoms of A to KEEP ---
    if mode == 'hull':
        from scipy.spatial import ConvexHull, Delaunay, KDTree
        # Compute hull on surface atoms of B if available
        if hasattr(NP_B, 'surfaceAtoms') and NP_B.surfaceAtoms is not None:
            pos_B_hull = pos_B[NP_B.surfaceAtoms]
        else:
            pos_B_hull = pos_B
        hull_B = ConvexHull(pos_B_hull)
        delaunay_B = Delaunay(pos_B_hull[hull_B.vertices])
        # Atoms strictly inside hull
        inside_hull = delaunay_B.find_simplex(pos_A) >= 0
        # Also keep atoms within cutoff of any surface atom of B
        # — avoids losing atoms just outside the hull but close to surface
        tree_surf = KDTree(pos_B_hull)
        dists_to_surf, _ = tree_surf.query(pos_A)
        near_surface = dists_to_surf < cutoff
        keep_mask = inside_hull | near_surface

    else:  # mode == 'atoms'
        from scipy.spatial import KDTree
        Rnn_A = getattr(self, 'Rnn', None)
        if Rnn_A is None:
            tree = KDTree(pos_A)
            dists, _ = tree.query(pos_A, k=2)
            Rnn_A = np.median(dists[:, 1])
            if not noOutput:
                print(f"  Rnn_A estimated: {Rnn_A:.3f} Å")
        cutoff = threshold * Rnn_A
        tree_B = KDTree(pos_B)
        dists, _ = tree_B.query(pos_A)
        keep_mask = dists < cutoff

    # --- Safety checks ---
    n_to_keep = int(np.count_nonzero(keep_mask))

    if n_to_keep == 0:
        print(f"\n{bg.DARKREDB}ERROR: no atoms of A are inside B — "
              f"operation cancelled.{bg.OFF}")
        print(f"  Check cogB position and mode='{mode}'.")
        return

    if n_to_keep == n_total:
        print(f"{bg.LIGHTYELLOWB}Warning: all atoms of A are inside B — "
              f"nothing changed. Check cogB position.{bg.OFF}")
        return

    # --- Apply mask ---
    self.NP = self.NP[keep_mask]

    # --- Invalidate old truncation planes ---
    # After intersection, the original planes are no longer valid
    # since the shape has fundamentally changed
    self.trPlanes      = None
    self.trPlanes_Wulff = None
    self.trPlanes_opt   = None
    # --- Recenter at origin ---
    if recenter:
        self.NP.positions -= self.NP.get_center_of_mass()

    # --- Update attributes ---
    self.nAtoms = len(self.NP)
    self.cog    = self.NP.get_center_of_mass()
    self._flush_stale_data(shape_update="_intersect")
    self.is_optimized = False

    if not noOutput:
        n_removed = n_total - n_to_keep
        print(f"  {n_removed} atoms removed, {self.nAtoms} remaining.")

    # --- Resolve parameters ---
    if postAnalyzis is None:
        postAnalyzis = getattr(self, 'postAnalyzis', True)
    if skipChiralityCalculation is None:
        skipChiralityCalculation = getattr(self, 'skipChiralityCalculation', True)
    if skipSymmetryAnalyzis is None:
        skipSymmetryAnalyzis = getattr(self, 'skipSymmetryAnalyzis', True)
    if skipFacetInfo is None:
        skipFacetInfo = getattr(self, 'skipFacetInfo', True)
    if thresholdCoreSurface is None:
        thresholdCoreSurface = getattr(self, 'thresholdCoreSurface', 3.0)

    if postAnalyzis:
        self.propPostMake(
            skipChiralityCalculation = skipChiralityCalculation,
            skipSymmetryAnalyzis     = skipSymmetryAnalyzis,
            skipFacetInfo            = skipFacetInfo,
            thresholdCoreSurface     = thresholdCoreSurface,
            noOutput                 = noOutput,
            is_optimized             = False,
        )

def flush_inlay_with(self,
                    NP_B,
                    cogB: list = None,
                    rotB=None,
                    mode: str = 'hull',
                    threshold: float = 0.8,
                    recenter: bool=True,
                    noOutput: bool = False,
                    postAnalyzis: bool = None,
                    skipChiralityCalculation: bool = None,
                    skipSymmetryAnalyzis: bool = None,
                    skipFacetInfo: bool = None,
                    thresholdCoreSurface: float = None,
             ):
    """
    Merge self.NP (object A) with the part of NP_B that overlaps with self.NP.
    Atoms of B outside A are discarded. Overlapping atoms are deduplicated.

    This is equivalent to:
        1. Keep only the atoms of B that are inside A (intersection of B with A).
        2. Add them to A, removing overlap within threshold * Rnn.

    Two modes are available:
    - 'hull' : the overlap region is defined by the convex hull of A.
    - 'atoms': atoms of B closer than threshold * Rnn to any atom of A
               are considered overlapping and added.

    Args:
        self: pyNMBcore object (A). Modified in place.
        NP_B: pyNMBcore object (B). Only the part inside A is added.
        cogB (list): Position in nm where the center of mass of B is placed
            before the operation. Default is None (B used as-is).
        rotB: Rotation applied to B before the operation, around its own
            center of mass. Accepts three forms:
            - None (default): no rotation.
            - [ux, uy, uz, angle]: single rotation — axis [ux, uy, uz]
              (Cartesian) and angle in degrees.
            - {'axis': [ux, uy, uz], 'angle': angle}: same as above.
            - [{'axis': [...], 'angle': ...}, ...]: list of rotations
              applied sequentially in the given order.
        mode (str): 'hull' (default) or 'atoms'.
        threshold (float): Distance threshold in units of Rnn for overlap
            detection and deduplication. Default is 0.8.
        recenter (bool): If True, recenters self.NP on its center of mass
            after slicing (default). Set to False when calling applySlicing
            multiple times in sequence (e.g. applying the same pattern on
            all 6 faces of a cube) to avoid shifting the reference frame
            between calls. In that case, recenter manually once at the end:
            NP.NP.positions -= NP.NP.get_center_of_mass()
        noOutput (bool): If True, suppresses output. Default is False.
        postAnalyzis (bool): If True, prints additional NP information.
        skipChiralityCalculation (bool): If True, skips the calculation of
            the OPD (Osipov-Pickup-Dunmur) chirality index.
        skipSymmetryAnalyzis (bool): If True, skips the symmetry analysis.
        skipFacetInfo (bool): If True, skips the external-facet info calculation.
        thresholdCoreSurface (float): Threshold used to distinguish core from
            surface atoms.

    Note:
        Updates self.NP, self.nAtoms and self.cog in place.
        Does not modify NP_B.
        The chemical species of B atoms are preserved in the merged structure.

    Example:
        # Merge the part of an octahedron that fits inside a cube
        AuCube.union(PtOh, cogB=[0, 0, 0.95], mode='hull')
    """
    if not noOutput:
        centertxt(f"CSG flush inlay (mode={mode})", bgc="#cbcbcb", size="12",
                  fgc="b", weight="bold")

    if mode not in ('hull', 'atoms'):
        print(f"{bg.LIGHTYELLOWB}Warning: unknown mode '{mode}', "
              f"defaulting to 'hull'.{bg.OFF}")
        mode = 'hull'

    # --- Position and rotate B ---
    pos_B = NP_B.NP.get_positions().copy()
    cog_B = NP_B.NP.get_center_of_mass()
    pos_B = pos_B - cog_B              # center B at origin
    pos_B = _apply_rotB(pos_B, rotB)   # rotate around its own center
    if cogB is not None:
        cogB_ang = np.array(cogB) * 10.0  # nm → Å
        pos_B = pos_B + cogB_ang

    # --- Positions of A ---
    pos_A = self.NP.get_positions()
    n_total_A = len(pos_A)

    # --- Estimate Rnn_A ---
    Rnn_A = getattr(self, 'Rnn', None)
    if Rnn_A is None:
        from scipy.spatial import KDTree
        tree = KDTree(pos_A)
        dists, _ = tree.query(pos_A, k=2)
        Rnn_A = np.median(dists[:, 1])
        if not noOutput:
            print(f"  Rnn_A estimated: {Rnn_A:.3f} Å")
    cutoff = threshold * Rnn_A

    # --- Step 1: keep only atoms of B inside A ---
    if mode == 'hull':
        from scipy.spatial import ConvexHull, Delaunay, KDTree
        # Compute hull on surface atoms of A if available
        if hasattr(self, 'surfaceAtoms') and self.surfaceAtoms is not None:
            pos_A_hull = pos_A[self.surfaceAtoms]
        else:
            pos_A_hull = pos_A
        hull_A = ConvexHull(pos_A_hull)
        delaunay_A = Delaunay(pos_A_hull[hull_A.vertices])

        # Atoms of B strictly inside hull of A
        inside_hull = delaunay_A.find_simplex(pos_B) >= 0
        # Also keep atoms of B within cutoff of surface of A
        tree_surf_A = KDTree(pos_A_hull)
        dists_to_surf, _ = tree_surf_A.query(pos_B)
        near_surface = dists_to_surf < cutoff
        keep_B_mask = inside_hull | near_surface

    else:  # mode == 'atoms'
        from scipy.spatial import KDTree
        tree_A = KDTree(pos_A)
        dists_B, _ = tree_A.query(pos_B)
        keep_B_mask = dists_B < cutoff
        
    n_B_kept = int(np.count_nonzero(keep_B_mask))

    if n_B_kept == 0:
        print(f"{bg.LIGHTYELLOWB}Warning: no atoms of B are inside A — "
              f"nothing added. Check cogB position.{bg.OFF}")
        return

    if not noOutput:
        print(f"  {n_B_kept}/{len(pos_B)} atoms of B are inside A.")

    pos_B_kept = pos_B[keep_B_mask]
    NP_B_kept  = NP_B.NP[keep_B_mask]
    NP_B_kept.set_positions(pos_B_kept)

    # --- Step 2: remove atoms of A that overlap with kept B atoms ---
    from scipy.spatial import KDTree
    tree_B_kept = KDTree(pos_B_kept)
    dists_A, _  = tree_B_kept.query(pos_A)
    overlap_A_mask = dists_A < cutoff
    n_removed_A = int(np.count_nonzero(overlap_A_mask))

    if not noOutput:
        print(f"  {n_removed_A} atoms of A removed (overlap within "
              f"{threshold:.2f} * Rnn = {cutoff:.3f} Å).")

    self.NP = self.NP[~overlap_A_mask]

    # --- Step 3: merge A (without overlaps) + kept B atoms ---
    import ase
    merged = self.NP + NP_B_kept

    # --- Invalidate old truncation planes ---
    self.trPlanes       = None
    self.trPlanes_Wulff = None
    self.trPlanes_opt   = None

    # --- Update attributes ---
    self.NP       = merged
    if recenter:
        self.NP.positions -= self.NP.get_center_of_mass()

    self.nAtoms   = len(self.NP)
    self.cog      = self.NP.get_center_of_mass()
    self._flush_stale_data(shape_update="_union")
    self.is_optimized = False

    if not noOutput:
        print(f"  {self.nAtoms} total atoms after inlay.")

    # --- Resolve parameters ---
    if postAnalyzis is None:
        postAnalyzis = getattr(self, 'postAnalyzis', True)
    if skipChiralityCalculation is None:
        skipChiralityCalculation = getattr(self, 'skipChiralityCalculation', True)
    if skipSymmetryAnalyzis is None:
        skipSymmetryAnalyzis = getattr(self, 'skipSymmetryAnalyzis', True)
    if skipFacetInfo is None:
        skipFacetInfo = getattr(self, 'skipFacetInfo', True)
    if thresholdCoreSurface is None:
        thresholdCoreSurface = getattr(self, 'thresholdCoreSurface', 3.0)

    if postAnalyzis:
        self.propPostMake(
            skipChiralityCalculation = skipChiralityCalculation,
            skipSymmetryAnalyzis     = skipSymmetryAnalyzis,
            skipFacetInfo            = skipFacetInfo,
            thresholdCoreSurface     = thresholdCoreSurface,
            noOutput                 = noOutput,
            is_optimized             = False,
        )