import time, datetime

import numpy as np

from .core import (pyNMB_location, get_resource_path, timer, RAB, Rbetween2Points,
                   vector, vectorBetween2Points, coord2xyz, vertex, vertexScaled, RadiusSphereAfterV,
                   centerOfGravity, center2cog, normOfV, normV, centerToVertices, Rx, Ry, Rz,
                   EulerRotationMatrix, plotPalette, rgb2hex, clone, deleteElementsOfAList,
                   planeFittingLSF, faces_to_planes, AngleBetweenVV, signedAngleBetweenVV
                   )
from .core import centertxt, centerTitle, fg, bg, hl, color
from .geometry import truncateAbovePlanes, setdAsNegative, rotationMolAroundAxis

import ase
#==================================================================================
#                          Constructive solid geometry
#==================================================================================

def applySlicing(self,
             planes,
             distance_unit: str = 'nm',
             mode: str = 'OR',
             recenter: bool=True,
             noOutput: bool = False,
             postAnalyzis: bool = None,
             skipChiralityCalculation: bool = None,
             skipSymmetryAnalyzis: bool = None,
             skipFacetInfo: bool = None,
             thresholdCoreSurface: float = None,
             ):
    """
    Apply one or more truncation plane groups to self.NP, with optional
    rotational symmetry generation and logical combination of groups.
    Works on any pyNMBcore object.

    Each plane group is defined by a dictionary. Within a group, planes are
    generated by rotational symmetry (nRot) around rotAxis, and combined
    according to the group-level 'modeP' key. Groups are then combined
    according to the top-level 'mode' parameter.

    Plane group keys:

        Plane definition (one of, mandatory):
            'normal' (array-like): Plane normal as a Cartesian vector [u, v, w]
                (if normal_def='cart', default) or Miller indices [h, k, l]
                (if normal_def='hkl', requires self.Gstar — Crystal objects only).
            'angle' (float): Angle in degrees between the plane normal and
                rotAxis. The reference normal is built from a starting
                direction (see 'startVec') rotated by this angle around rotAxis.

        Mandatory keys:
            'distance' (float): Signed orthogonal distance from the origin
                (center of mass of the NP) to the truncation plane, in nm
                (default) or Å (distance_unit), along the plane normal n.
                The plane is defined by n · x = distance, where x is any
                point on the plane.
                - distance > 0 : plane is on the positive side of n,
                                 at distance Å from the origin.
                - distance = 0 : plane passes through the origin.
                - distance < 0 : plane is on the negative side of n,
                                 at |distance| Å from the origin.
            'delete' (str): Which atoms to remove.
                'above' removes atoms on the positive side of the plane normal.
                'below' removes atoms on the negative side.
                Default is 'above'.

        Optional keys:
            'normal_def' (str): Coordinate system for 'normal'. Either 'cart'
                (Cartesian, default) or 'hkl' (Miller indices, Crystal only).
            'nRot' (int): Number of planes generated by rotation around rotAxis.
                Rotation angle = 360° / nRot. Default is 1 (no rotation).
            'rotAxis' (array-like): Rotation axis as a Cartesian vector.
                Required if nRot > 1.
            'startVec' (array-like, optional): Starting direction used to build
                the reference normal in 'angle' mode. Only its component
                perpendicular to rotAxis is used, so it need not be orthogonal
                to rotAxis — but it must not be collinear with it. If omitted,
                an arbitrary perpendicular direction is chosen.
            'startAngle' (float, optional): Azimuth in degrees, around rotAxis,
                of the in-plane reference direction, measured from 'refVec'.
                Mutually exclusive with 'startVec' (error if both are given).
            'refVec' (array-like, optional): Direction defining the 0° azimuth
                for 'startAngle'. Only its component perpendicular to rotAxis is
                used; must not be collinear with rotAxis. Only valid together
                with 'startAngle'. Defaults to an arbitrary perpendicular.
            'modeP' (str): Logical combination of planes within this group.
                'OR'  — atom removed if condemned by ANY plane in the group.
                        Default when side='above'. Use for faceting.
                'AND' — atom removed only if condemned by ALL planes in the group
                        simultaneously. Default when side='below'.
                        Use for concave holes or pyramidal cavities.

    Args:
        planes (list of dict): List of plane group definitions (see above).
        distance_unit (str): Unit for all distances. 'nm' (default) or
            'Angstrom'.
        mode (str): Logical combination of plane groups.
            'OR'  — atom removed if condemned by ANY group (default).
                    Use for standard faceting or combined truncations.
            'AND' — atom removed only if condemned by ALL groups simultaneously.
                    Use for complex intersections.
        recenter (bool): If True, recenters self.NP on its center of mass
            after slicing (default). Set to False when calling applySlicing
            multiple times in sequence (e.g. applying the same pattern on
            all 6 faces of a cube) to avoid shifting the reference frame
            between calls. In that case, recenter manually once at the end:
            NP.NP.positions -= NP.NP.get_center_of_mass()
        noOutput (bool): If True, suppresses all printed output.
            Default is False.
        postAnalyzis (bool): If True, prints additional NP information.
        skipChiralityCalculation (bool): If True, skips the calculation of
            the OPD (Osipov-Pickup-Dunmur) chirality index.
        skipSymmetryAnalyzis (bool): If True, skips the symmetry analysis.
        skipFacetInfo (bool): If True, skips the external-facet info calculation.
        thresholdCoreSurface (float): Threshold used to distinguish core from
            surface atoms.
            
    Note:
        Updates self.NP, self.nAtoms and self.cog in place.
        self.trPlanes_Slices is updated with all applied truncation planes.
        self.trPlanes_Wulff is set to None (not a Wulff construction).
        A recentering on the center of mass is applied after all truncations.
        If the operation would delete all atoms, it is cancelled and a
        detailed summary of each group is printed to help diagnose the issue.

    Examples:
        # Facet a cube with 4 {010} planes (OR mode, default)
        NP.applySlicing(
            planes=[
                {'normal': [0, 1, 0], 'distance': 6.0,
                 'nRot': 4, 'rotAxis': [0, 0, 1], 'delete': 'above'},
            ],
            distance_unit='Angstrom'
        )

        # Carve a pyramidal hole on top of a cube
        NP.applySlicing(
            planes=[
                {'normal': [0, 1, 1], 'distance': 5.0,
                 'nRot': 4, 'rotAxis': [0, 0, 1],
                 'delete': 'below', 'modeP': 'AND'},
            ],
            distance_unit='Angstrom'
        )

        # Facet AND cut a top slice simultaneously (AND between groups)
        NP.applySlicing(
            planes=[
                {'normal': [0, 1, 0], 'distance': 6.0,
                 'nRot': 4, 'rotAxis': [0, 0, 1], 'delete': 'above'},
                {'normal': [0, 0, 1], 'distance': 6.0,
                 'nRot': 1, 'delete': 'above'},
            ],
            mode='AND',
            distance_unit='Angstrom'
        )
    """
    if not noOutput:
        centertxt(f"Slicing operation (mode={mode})", bgc="#cbcbcb", size="12",
                  fgc="b", weight="bold")

    if mode not in ('OR', 'AND'):
        print(f"{bg.LIGHTYELLOWB}Warning: unknown mode '{mode}', "
              f"defaulting to 'OR'.{bg.OFF}")
        mode = 'OR'

    # --- Unit conversion ---
    scale = 10.0 if distance_unit == 'nm' else 1.0  # nm → Å

    all_tr_planes = []
    group_masks   = []
    group_summaries = []   # for error reporting

    for plane_def in planes:

        # --- Side to delete --- backward compatibility with 'side'
        if 'side' in plane_def and 'delete' not in plane_def:
            delete = plane_def['side']  # legacy alias
        else:
            delete = plane_def.get('delete', 'above')
            
        # --- Distance ---
        distance_ang = plane_def['distance'] * scale

        # --- Side 2 delete---
        delete = plane_def.get('delete', 'above')
        if delete not in ('above', 'below'):
            print(f"{bg.LIGHTYELLOWB}Warning: unknown side to delete '{delete}', "
                  f"defaulting to 'above'.{bg.OFF}")
            delete = 'above'
        del_above = (delete == 'above')

        # --- modeP within group ---
        default_modeP = 'AND' if delete == 'below' else 'OR'
        modeP = plane_def.get('modeP', default_modeP)
        if modeP not in ('OR', 'AND'):
            print(f"{bg.LIGHTYELLOWB}Warning: unknown modeP '{modeP}', "
                  f"defaulting to '{default_modeP}'.{bg.OFF}")
            modeP = default_modeP
        allP_group = (modeP == 'AND')

        # --- Build reference normal in Cartesian ---
        if 'normal' in plane_def:
            normal_def = plane_def.get('normal_def', 'cart')
            n = np.array(plane_def['normal'], dtype=float)
            if normal_def == 'hkl':
                if not hasattr(self, 'Gstar'):
                    raise AttributeError(
                        "normal_def='hkl' requires a Crystal object with "
                        "self.Gstar. Use normal_def='cart' instead.")
                from .crystals import lattice_cart
                n = lattice_cart(self, [n], Bravais2cart=True)[0]
            n = n / np.linalg.norm(n)

        elif 'angle' in plane_def:
            rot_axis = np.array(plane_def['rotAxis'], dtype=float)
            rot_axis = rot_axis / np.linalg.norm(rot_axis)
            angle_deg = plane_def['angle']

            def _project_perp(vec, name):
                """Component of `vec` perpendicular to rot_axis, normalized."""
                v = np.array(vec, dtype=float)
                if np.linalg.norm(v) < 1e-12:
                    raise ValueError(f"'{name}' must be a non-zero vector.")
                v = v / np.linalg.norm(v)
                p = v - np.dot(v, rot_axis) * rot_axis
                if np.linalg.norm(p) < 1e-8:
                    raise ValueError(
                        f"'{name}' is collinear with 'rotAxis'; it has no "
                        f"component in the plane perpendicular to the axis.")
                return p / np.linalg.norm(p)

            # In-plane reference direction (the "meridian"), defined by ONE of:
            #   - 'startVec'  : given directly as a vector
            #   - 'startAngle': azimuth (deg) around rotAxis from 'refVec'
            #                   (refVec defaults to an arbitrary perpendicular)
            #   - neither     : arbitrary perpendicular (previous default)
            if 'startVec' in plane_def and 'startAngle' in plane_def:
                raise ValueError(
                    "Provide either 'startVec' or 'startAngle', not both.")

            if 'startVec' in plane_def:
                perp = _project_perp(plane_def['startVec'], 'startVec')
            elif 'startAngle' in plane_def:
                if 'refVec' in plane_def:
                    ref = _project_perp(plane_def['refVec'], 'refVec')
                else:
                    arbitrary = np.array([1, 0, 0]) if abs(rot_axis[0]) < 0.9 \
                                else np.array([0, 1, 0])
                    ref = np.cross(rot_axis, arbitrary)
                    ref = ref / np.linalg.norm(ref)
                perp = rotationMolAroundAxis(ref, plane_def['startAngle'], rot_axis)
                perp = perp / np.linalg.norm(perp)
            else:
                if 'refVec' in plane_def:
                    raise ValueError(
                        "'refVec' is only meaningful together with "
                        "'startAngle'.")
                arbitrary = np.array([1, 0, 0]) if abs(rot_axis[0]) < 0.9 \
                            else np.array([0, 1, 0])
                perp = np.cross(rot_axis, arbitrary)
                perp = perp / np.linalg.norm(perp)

            # Tilt the meridian towards +rotAxis by 'angle' (0° = radial).
            tilt_axis = np.cross(perp, rot_axis)
            tilt_axis = tilt_axis / np.linalg.norm(tilt_axis)
            n = rotationMolAroundAxis(perp, angle_deg, tilt_axis)
            n = n / np.linalg.norm(n)
        else:
            raise ValueError(
                "Each plane definition must contain either 'normal' or 'angle'.")

        # --- Generate rotational family ---
        nRot = plane_def.get('nRot', 1)
        if nRot < 1:
            print(f"{bg.LIGHTYELLOWB}Warning: nRot={nRot} is invalid, "
                  f"set to 1.{bg.OFF}")
            nRot = 1

        if nRot > 1:
            rot_axis = np.array(plane_def['rotAxis'], dtype=float)
            rot_axis = rot_axis / np.linalg.norm(rot_axis)
            normals = [rotationMolAroundAxis(n, i * 360.0 / nRot, rot_axis)
                       for i in range(nRot)]
        else:
            normals = [n]

        # --- Build plane equations [nx, ny, nz, d] with d < 0 ---
        family_planes = []
        for nn in normals:
            nn = nn / np.linalg.norm(nn)
            plane_eq = np.append(nn, -distance_ang)
            all_tr_planes.append(plane_eq)
            family_planes.append(plane_eq)
        family_planes = np.array(family_planes)

        if not noOutput:
            normal_label = plane_def.get('normal', None)
            if normal_label is None:
                normal_label = f"angle={plane_def.get('angle')}"
            print(f"\n  Group {len(group_masks)+1} — "
                  f"normal: {normal_label}"
                  f"  nRot: {nRot}  distance: {plane_def['distance']} {distance_unit}"
                  f"  side to delete: {delete}  modeP: {modeP}")
            for nn in normals:
                nn_n = nn / np.linalg.norm(nn)
                print(f"    [{nn_n[0]:+.4f} {nn_n[1]:+.4f} {nn_n[2]:+.4f}]"
                      f"  d = {distance_ang:.3f} Å")

        # --- Compute group mask ---
        group_mask = truncateAbovePlanes(
            family_planes,
            self.NP.positions,
            allP=allP_group,
            delAbove=del_above,
            eps=getattr(self, 'threshold', 1e-3),
            debug=False,
            noOutput=True,
        )
        group_masks.append(group_mask)
        group_summaries.append({
            'normal': plane_def.get('normal', f"angle={plane_def.get('angle')}"),
            'distance': plane_def['distance'],
            'delete': delete,
            'modeP': modeP,
            'nRot': nRot,
            'n_condemned': int(np.count_nonzero(group_mask)),
        })

    # --- Combine group masks according to mode ---
    if len(group_masks) == 0:
        if not noOutput:
            print("No planes defined — nothing to do.")
        return

    if mode == 'OR':
        final_mask = group_masks[0]
        for m in group_masks[1:]:
            final_mask = final_mask | m
    else:  # 'AND'
        final_mask = group_masks[0]
        for m in group_masks[1:]:
            final_mask = final_mask & m

    # --- Safety check: would all atoms be deleted? ---
    n_total  = len(self.NP)
    n_to_del = int(np.count_nonzero(final_mask))

    if n_to_del == n_total:
        print(f"\n{bg.DARKREDB}ERROR: all {n_total} atoms would be deleted! "
              f"Operation cancelled.{bg.OFF}")
        print(f"\n{bg.LIGHTYELLOWB}Summary of plane groups:{bg.OFF}")
        print(f"  Global mode : {mode}")
        print(f"  {'Group':<6} {'normal':<20} {'distance':>10} "
              f"{'delete':<8} {'modeP':<6} {'nRot':<6} {'condemned':>10}")
        print(f"  {'─'*70}")
        for i, s in enumerate(group_summaries):
            print(f"  {i+1:<6} {str(s['normal']):<20} "
                  f"{s['distance']:>8.3f} {distance_unit}  "
                  f"{s['delete']:<8} {s['modeP']:<6} {s['nRot']:<6} "
                  f"{s['n_condemned']:>6}/{n_total}")
        print(f"\n{bg.LIGHTYELLOWB}Hints:{bg.OFF}")
        print(f"  - Check distances (too small → plane inside NP → everything condemned)")
        print(f"  - Check delete ('above' vs 'below')")
        print(f"  - Check modeP ('OR' vs 'AND') within each group")
        print(f"  - Check mode ('OR' vs 'AND') between groups")
        return

    # --- Apply final mask ---
    self.NP = self.NP[~final_mask]

    group_info = []
    delete_by_plane = []
    for i, plane_def in enumerate(planes):
        nRot = plane_def.get('nRot', 1)
        if 'side' in plane_def and 'delete' not in plane_def:
            d = plane_def['side']  # backward compatibility
        else:
            d = plane_def.get('delete', 'above')
        for _ in range(nRot):
            group_info.append(i)
            delete_by_plane.append(d)
    
    self.trPlanes_Slicing_groups = group_info
    self.trPlanes_Slicing_delete = delete_by_plane

    # --- Recenter ---
    if recenter:
        com_shift = self.NP.get_center_of_mass()  # ← avant le recentrage !
        self.NP.positions -= com_shift
        # Update plane distances to account for recentering
        if len(all_tr_planes) > 0:
            all_tr_planes_arr = np.array(all_tr_planes)
            for i, plane in enumerate(all_tr_planes_arr):
                n = plane[:3]
                # New d = old d + n · shift
                all_tr_planes_arr[i, 3] += np.dot(n, com_shift)
            all_tr_planes = all_tr_planes_arr.tolist()

    # --- Update attributes ---
    self.trPlanes_Slices  = setdAsNegative(np.array(all_tr_planes))
    self.trPlanes_Wulff   = None
    self.nAtoms           = len(self.NP)
    self.cog              = self.NP.get_center_of_mass()
    self._flush_stale_data(shape_update="_Slices")
    self.is_optimized     = False
    
    if not noOutput:
        print(f"  {n_to_del} atoms removed, {self.nAtoms} remaining.")
        
    # --- Resolve parameters ---
    if postAnalyzis is None:
        postAnalyzis = getattr(self, 'postAnalyzis', True)
    if skipChiralityCalculation is None:
        skipChiralityCalculation = getattr(self, 'skipChiralityCalculation', True)
    if skipSymmetryAnalyzis is None:
        skipSymmetryAnalyzis = getattr(self, 'skipSymmetryAnalyzis', True)
    if skipFacetInfo is None:
        skipFacetInfo = getattr(self, 'skipFacetInfo', True)
    if thresholdCoreSurface is None:
        thresholdCoreSurface = getattr(self, 'thresholdCoreSurface', 3.0)

    if postAnalyzis:
        self.propPostMake(
            skipChiralityCalculation = skipChiralityCalculation,
            skipSymmetryAnalyzis     = skipSymmetryAnalyzis,
            skipFacetInfo            = skipFacetInfo,
            thresholdCoreSurface     = thresholdCoreSurface,
            noOutput                 = noOutput,
            is_optimized             = False,
        )

def _apply_rotB(pos_B, rotB):
    """
    Apply one or more rotations to positions pos_B.
    rotB can be:
      - None                          : no rotation
      - [ux, uy, uz, angle]           : single rotation, axis + angle in degrees
      - {'axis': [...], 'angle': ...} : single rotation as dict
      - [{'axis': [...], 'angle': ...}, ...] : list of rotations applied in order
    """
    if rotB is None:
        return pos_B

    # Normalize to a list of dicts
    if isinstance(rotB, (list, np.ndarray)) and len(rotB) == 4 and not isinstance(rotB[0], dict):
        # [ux, uy, uz, angle] shorthand
        rotations = [{'axis': list(rotB[:3]), 'angle': float(rotB[3])}]
    elif isinstance(rotB, dict):
        rotations = [rotB]
    elif isinstance(rotB, list) and isinstance(rotB[0], dict):
        rotations = rotB
    else:
        raise ValueError(
            "rotB must be [ux, uy, uz, angle], a dict {'axis':..., 'angle':...}, "
            "or a list of such dicts.")

    # Apply rotations in order
    for rot in rotations:
        axis  = np.array(rot['axis'], dtype=float)
        angle = float(rot['angle'])
        axis  = axis / np.linalg.norm(axis)
        pos_B = rotationMolAroundAxis(pos_B, angle, axis)

    return pos_B
    
def cut_by(self,
            NP_B,
            cogB: list = None,
            rotB=None,
            mode: str = 'hull',
            threshold: float = 0.8,
            recenter: bool=True,
            noOutput: bool = False,
            postAnalyzis: bool = None,
            skipChiralityCalculation: bool = None,
            skipSymmetryAnalyzis: bool = None,
            skipFacetInfo: bool = None,
            thresholdCoreSurface: float = None,
             ):
    """
    Remove from self.NP (object A) the atoms that lie inside object B,
    creating a hollow cavity in the shape of B.

    Two modes are available:
    - 'hull' : atoms of A inside the convex hull of B are removed.
               Fast and geometrically exact for convex shapes.
    - 'atoms': atoms of A closer than threshold * Rnn to any atom of B
               are removed. Works for any shape, respects the atomic lattice.

    Args:
        self: pyNMBcore object (A). Modified in place.
        NP_B: pyNMBcore object (B). Defines the cavity shape.
        cogB (list): Position in nm where the center of mass of B is placed
            before the operation. Default is None (B used as-is).
        rotB: Rotation applied to B before the operation, around its own
            center of mass. Accepts three forms:
            - None (default): no rotation.
            - [ux, uy, uz, angle]: single rotation — axis [ux, uy, uz]
              (Cartesian) and angle in degrees.
              Example: [0, 0, 1, 45.0] rotates B by 45° around z.
            - {'axis': [ux, uy, uz], 'angle': angle}: same as above,
              as a dictionary.
            - [{'axis': [...], 'angle': ...}, ...]: list of rotations
              applied sequentially in the given order.
              Example: [{'axis': [0,0,1], 'angle': 45.0},
                        {'axis': [1,0,0], 'angle': 30.0}]
              rotates B first by 45° around z, then by 30° around x.
        mode (str): 'hull' (default) or 'atoms'.
        threshold (float): Only for mode='atoms'. Atoms of A closer than
            threshold * Rnn_A to any atom of B are removed. Default is 0.8.
        recenter (bool): If True, recenters self.NP on its center of mass
            after slicing (default). Set to False when calling applySlicing
            multiple times in sequence (e.g. applying the same pattern on
            all 6 faces of a cube) to avoid shifting the reference frame
            between calls. In that case, recenter manually once at the end:
            NP.NP.positions -= NP.NP.get_center_of_mass()
        noOutput (bool): If True, suppresses output. Default is False.
        postAnalyzis (bool): If True, prints additional NP information.
        skipChiralityCalculation (bool): If True, skips the calculation of
            the OPD (Osipov-Pickup-Dunmur) chirality index.
        skipSymmetryAnalyzis (bool): If True, skips the symmetry analysis.
        skipFacetInfo (bool): If True, skips the external-facet info calculation.
        thresholdCoreSurface (float): Threshold used to distinguish core from
            surface atoms.

    Note:
        Updates self.NP, self.nAtoms and self.cog in place.
        Does not modify NP_B.

    Example:
        # Create a spherical hollow in a gold cube
        AuCube  = pNP.cube(element='Au', ...)
        PtSphere = Crystal('Pt fcc', shape='sphere', size=[2])
        AuCube.minus(PtSphere, cogB=[0, 0, 0], mode='hull')
    """
    if not noOutput:
        centertxt(f"CSG minus (mode={mode})", bgc="#cbcbcb", size="12",
                  fgc="b", weight="bold")

    if mode not in ('hull', 'atoms'):
        print(f"{bg.LIGHTYELLOWB}Warning: unknown mode '{mode}', "
              f"defaulting to 'hull'.{bg.OFF}")
        mode = 'hull'

    # --- Position B at cogB ---
    pos_B = NP_B.NP.get_positions().copy()
    cog_B = NP_B.NP.get_center_of_mass()
    # --- Rotate B around its own center of mass, then translate ---
    pos_B = pos_B - cog_B          # center B at origin before rotation
    pos_B = _apply_rotB(pos_B, rotB)  # rotate
    if cogB is not None:
        cogB_ang = np.array(cogB) * 10.0  # nm → Å
        pos_B = pos_B - cog_B + cogB_ang  # shift B to cogB

    # --- Positions of A ---
    pos_A = self.NP.get_positions()
    n_total = len(pos_A)

    # --- Compute mask: atoms of A to remove ---
    # --- Estimate Rnn_A --- needed for both modes
    Rnn_A = getattr(self, 'Rnn', None)
    if Rnn_A is None:
        from scipy.spatial import KDTree
        tree = KDTree(pos_A)
        dists, _ = tree.query(pos_A, k=2)
        Rnn_A = np.median(dists[:, 1])
        if not noOutput:
            print(f"  Rnn_A estimated: {Rnn_A:.3f} Å")
    cutoff = threshold * Rnn_A

    if mode == 'hull':
        from scipy.spatial import ConvexHull, Delaunay, KDTree
        # Compute hull on surface atoms of B if available
        if hasattr(NP_B, 'surfaceAtoms') and NP_B.surfaceAtoms is not None:
            pos_B_hull = pos_B[NP_B.surfaceAtoms]
        else:
            pos_B_hull = pos_B
        hull_B = ConvexHull(pos_B_hull)
        delaunay_B = Delaunay(pos_B_hull[hull_B.vertices])
        # Atoms strictly inside hull
        inside_hull = delaunay_B.find_simplex(pos_A) >= 0
        # Also remove atoms within cutoff of any surface atom of B
        tree_surf = KDTree(pos_B_hull)
        dists_to_surf, _ = tree_surf.query(pos_A)
        near_surface = dists_to_surf < cutoff
        inside_mask = inside_hull | near_surface
    else:  # mode == 'atoms'
        from scipy.spatial import KDTree
        Rnn_A = getattr(self, 'Rnn', None)
        if Rnn_A is None:
            # Estimate Rnn from nearest neighbor distances
            tree = KDTree(pos_A)
            dists, _ = tree.query(pos_A, k=2)
            Rnn_A = np.median(dists[:, 1])
            if not noOutput:
                print(f"  Rnn_A estimated: {Rnn_A:.3f} Å")
        cutoff = threshold * Rnn_A
        tree_B = KDTree(pos_B)
        dists, _ = tree_B.query(pos_A)
        inside_mask = dists < cutoff

    # --- Safety check ---
    n_to_del = int(np.count_nonzero(inside_mask))
    if n_to_del == n_total:
        print(f"\n{bg.DARKREDB}ERROR: all {n_total} atoms of A would be "
              f"deleted! Operation cancelled.{bg.OFF}")
        print(f"  Check cogB position and mode='{mode}'.")
        return

    if n_to_del == 0:
        print(f"{bg.LIGHTYELLOWB}Warning: no atoms removed — "
              f"B may not overlap with A. Check cogB position.{bg.OFF}")
        return

    # --- Apply mask ---
    self.NP = self.NP[~inside_mask]

    # --- Remove isolated/undercoordinated atoms after cut ---
    # Atoms left floating after the cut (e.g. at cavity edges) are removed
    from .geometry import peel_by_coordination
    n_before = len(self.NP)
    peel_by_coordination(self,
                         threshold_peeling=1,  # remove only truly isolated atoms
                         Rmax=1.2 * Rnn_A,
                         postAnalyzis=False,
                         noOutput=True)
    n_removed_isolated = n_before - len(self.NP)
    if not noOutput and n_removed_isolated > 0:
        print(f"{bg.LIGHTYELLOWB}Warning: {n_removed_isolated} isolated "
              f"atom(s) removed after cut.{bg.OFF}")
        
    # --- Invalidate old truncation planes ---
    # After intersection, the original planes are no longer valid
    # since the shape has fundamentally changed
    self.trPlanes      = None
    self.trPlanes_Wulff = None
    self.trPlanes_opt   = None
    # --- Recenter at origin ---
    if recenter:
        self.NP.positions -= self.NP.get_center_of_mass()

    # --- Update attributes ---
    self.nAtoms = len(self.NP)
    self.cog    = self.NP.get_center_of_mass()
    self._flush_stale_data(shape_update="_hollow")
    self.is_optimized = False

    if not noOutput:
        print(f"  {n_to_del} atoms removed from A, "
              f"{self.nAtoms} remaining.")

    # --- Resolve parameters ---
    if postAnalyzis is None:
        postAnalyzis = getattr(self, 'postAnalyzis', True)
    if skipChiralityCalculation is None:
        skipChiralityCalculation = getattr(self, 'skipChiralityCalculation', True)
    if skipSymmetryAnalyzis is None:
        skipSymmetryAnalyzis = getattr(self, 'skipSymmetryAnalyzis', True)
    if skipFacetInfo is None:
        skipFacetInfo = getattr(self, 'skipFacetInfo', True)
    if thresholdCoreSurface is None:
        thresholdCoreSurface = getattr(self, 'thresholdCoreSurface', 3.0)

    if postAnalyzis:
        self.propPostMake(
            skipChiralityCalculation = skipChiralityCalculation,
            skipSymmetryAnalyzis     = skipSymmetryAnalyzis,
            skipFacetInfo            = skipFacetInfo,
            thresholdCoreSurface     = thresholdCoreSurface,
            noOutput                 = noOutput,
            is_optimized             = False,
        )

def union_with(self,
                NP_B,
                cogB: list = None,
                rotB=None,
                mode: str = 'hull',
                threshold: float = 0.8,
                recenter: bool=True,
                noOutput: bool = False,
                postAnalyzis: bool = None,
                skipChiralityCalculation: bool = None,
                skipSymmetryAnalyzis: bool = None,
                skipFacetInfo: bool = None,
                thresholdCoreSurface: float = None,
             ):
    """
    Add NP_B to self.NP (object A), removing overlapping atoms closer
    than threshold * Rnn to avoid unphysical interatomic distances.

    The atoms of B are placed at cogB, optionally rotated by rotB, then
    merged with A. Atoms of A closer than threshold * Rnn to any atom of B
    are removed before merging to avoid overlap.

    Args:
        self: pyNMBcore object (A). Modified in place.
        NP_B: pyNMBcore object (B). Added to A.
        cogB (list): Position in nm where the center of mass of B is placed
            before the operation. Default is None (B used as-is).
        rotB: Rotation applied to B before the operation, around its own
            center of mass. Accepts three forms:
            - None (default): no rotation.
            - [ux, uy, uz, angle]: single rotation — axis [ux, uy, uz]
              (Cartesian) and angle in degrees.
            - {'axis': [ux, uy, uz], 'angle': angle}: same as above.
            - [{'axis': [...], 'angle': ...}, ...]: list of rotations
              applied sequentially in the given order.
        mode (str): 'hull' (default) or 'atoms'.
        threshold (float): Atoms of A closer than threshold * Rnn_A to any
            atom of B are removed before merging. Default is 0.8.
        recenter (bool): If True, recenters self.NP on its center of mass
            after slicing (default). Set to False when calling applySlicing
            multiple times in sequence (e.g. applying the same pattern on
            all 6 faces of a cube) to avoid shifting the reference frame
            between calls. In that case, recenter manually once at the end:
            NP.NP.positions -= NP.NP.get_center_of_mass()
        noOutput (bool): If True, suppresses output. Default is False.
        postAnalyzis (bool): If True, prints additional NP information.
        skipChiralityCalculation (bool): If True, skips the calculation of
            the OPD (Osipov-Pickup-Dunmur) chirality index.
        skipSymmetryAnalyzis (bool): If True, skips the symmetry analysis.
        skipFacetInfo (bool): If True, skips the external-facet info calculation.
        thresholdCoreSurface (float): Threshold used to distinguish core from
            surface atoms.

    Note:
        Updates self.NP, self.nAtoms and self.cog in place.
        Does not modify NP_B.
        The chemical species of B atoms are preserved in the merged structure.

    Example:
        # Insert a Pt octahedron into a hollow Au cube
        AuCube.minus(PtOh, cogB=[0, 0, 0], mode='atoms', threshold=0.8)
        AuCube.plus(PtOh,  cogB=[0, 0, 0], threshold=0.8)
    """
    if not noOutput:
        centertxt("CSG plus", bgc="#cbcbcb", size="12",
                  fgc="b", weight="bold")

    # --- Position and rotate B ---
    pos_B = NP_B.NP.get_positions().copy()
    cog_B = NP_B.NP.get_center_of_mass()
    pos_B = pos_B - cog_B              # center B at origin
    pos_B = _apply_rotB(pos_B, rotB)   # rotate around its own center
    if cogB is not None:
        cogB_ang = np.array(cogB) * 10.0  # nm → Å
        pos_B = pos_B + cogB_ang

    # --- Estimate Rnn_A ---
    pos_A = self.NP.get_positions()
    Rnn_A = getattr(self, 'Rnn', None)
    if Rnn_A is None:
        from scipy.spatial import KDTree
        tree = KDTree(pos_A)
        dists, _ = tree.query(pos_A, k=2)
        Rnn_A = np.median(dists[:, 1])
        if not noOutput:
            print(f"  Rnn_A estimated: {Rnn_A:.3f} Å")

    cutoff = threshold * Rnn_A

    # --- Remove atoms of A that overlap with B ---
    if mode == 'hull':
        from scipy.spatial import ConvexHull, Delaunay, KDTree

        # Compute hull only on surface atoms of B if available
        # — much faster than using all atoms
        if hasattr(NP_B, 'surfaceAtoms') and NP_B.surfaceAtoms is not None:
            pos_B_hull = pos_B[NP_B.surfaceAtoms]
        else:
            pos_B_hull = pos_B

        hull_B = ConvexHull(pos_B_hull)
        delaunay_B = Delaunay(pos_B_hull[hull_B.vertices])

        # Atoms strictly inside hull
        inside_hull = delaunay_B.find_simplex(pos_A) >= 0

        # Also remove atoms of A within cutoff of ANY surface atom of B
        # — hull vertices alone are not enough (only corners, missing most surface)
        if hasattr(NP_B, 'surfaceAtoms') and NP_B.surfaceAtoms is not None:
            pos_B_surface = pos_B[NP_B.surfaceAtoms]
        else:
            pos_B_surface = pos_B
        tree_surf = KDTree(pos_B_surface)
        dists_to_surf, _ = tree_surf.query(pos_A)
        near_surface = dists_to_surf < cutoff
        overlap_mask = inside_hull | near_surface

    else:  # mode == 'atoms'
        from scipy.spatial import KDTree
        tree_B = KDTree(pos_B)
        dists_A, _ = tree_B.query(pos_A)
        overlap_mask = dists_A < cutoff
        
    n_removed = int(np.count_nonzero(overlap_mask))
    if not noOutput:
        print(f"  {n_removed} atoms of A removed (overlap within "
              f"{threshold:.2f} * Rnn = {cutoff:.3f} Å)")

    self.NP = self.NP[~overlap_mask]

    # --- Build merged ASE Atoms object ---
    NP_B_shifted = NP_B.NP.copy()
    NP_B_shifted.set_positions(pos_B)

    merged = self.NP + NP_B_shifted

    # --- Update attributes ---
    self.NP     = merged
    self.nAtoms = len(self.NP)

    # --- Invalidate old truncation planes ---
    # After intersection, the original planes are no longer valid
    # since the shape has fundamentally changed
    self.trPlanes      = None
    self.trPlanes_Wulff = None
    self.trPlanes_opt   = None
    # --- Recenter at origin ---
    if recenter: 
        self.NP.positions -= self.NP.get_center_of_mass()
    
    self.cog    = self.NP.get_center_of_mass()
    self._flush_stale_data(shape_update="_plus")
    self.is_optimized = False

    if not noOutput:
        print(f"  {len(NP_B_shifted)} atoms of B added, "
              f"{self.nAtoms} total atoms.")

    # --- Resolve parameters ---
    if postAnalyzis is None:
        postAnalyzis = getattr(self, 'postAnalyzis', True)
    if skipChiralityCalculation is None:
        skipChiralityCalculation = getattr(self, 'skipChiralityCalculation', True)
    if skipSymmetryAnalyzis is None:
        skipSymmetryAnalyzis = getattr(self, 'skipSymmetryAnalyzis', True)
    if skipFacetInfo is None:
        skipFacetInfo = getattr(self, 'skipFacetInfo', True)
    if thresholdCoreSurface is None:
        thresholdCoreSurface = getattr(self, 'thresholdCoreSurface', 3.0)

    if postAnalyzis:
        self.propPostMake(
            skipChiralityCalculation = skipChiralityCalculation,
            skipSymmetryAnalyzis     = skipSymmetryAnalyzis,
            skipFacetInfo            = skipFacetInfo,
            thresholdCoreSurface     = thresholdCoreSurface,
            noOutput                 = noOutput,
            is_optimized             = False,
        )

def intersect_with(self,
                    NP_B,
                    cogB: list = None,
                    rotB=None,
                    mode: str = 'hull',
                    threshold: float = 0.8,
                    recenter: bool=True,
                    noOutput: bool = False,
                    postAnalyzis: bool = None,
                    skipChiralityCalculation: bool = None,
                    skipSymmetryAnalyzis: bool = None,
                    skipFacetInfo: bool = None,
                    thresholdCoreSurface: float = None,
             ):
    """
    Keep in self.NP (object A) only the atoms that lie inside object B,
    discarding everything outside.

    Two modes are available:
    - 'hull' : only atoms of A inside the convex hull of B are kept.
               Fast and geometrically exact for convex shapes.
    - 'atoms': only atoms of A closer than threshold * Rnn to any atom
               of B are kept. Works for any shape.

    Args:
        self: pyNMBcore object (A). Modified in place.
        NP_B: pyNMBcore object (B). Defines the intersection region.
        cogB (list): Position in nm where the center of mass of B is placed
            before the operation. Default is None (B used as-is).
        rotB: Rotation applied to B before the operation, around its own
            center of mass. Accepts three forms:
            - None (default): no rotation.
            - [ux, uy, uz, angle]: single rotation — axis [ux, uy, uz]
              (Cartesian) and angle in degrees.
            - {'axis': [ux, uy, uz], 'angle': angle}: same as above.
            - [{'axis': [...], 'angle': ...}, ...]: list of rotations
              applied sequentially in the given order.
        mode (str): 'hull' (default) or 'atoms'.
        threshold (float): Only for mode='atoms'. Atoms of A closer than
            threshold * Rnn_A to any atom of B are kept. Default is 0.8.
        recenter (bool): If True, recenters self.NP on its center of mass
            after slicing (default). Set to False when calling applySlicing
            multiple times in sequence (e.g. applying the same pattern on
            all 6 faces of a cube) to avoid shifting the reference frame
            between calls. In that case, recenter manually once at the end:
            NP.NP.positions -= NP.NP.get_center_of_mass()
        noOutput (bool): If True, suppresses output. Default is False.
        postAnalyzis (bool): If True, prints additional NP information.
        skipChiralityCalculation (bool): If True, skips the calculation of
            the OPD (Osipov-Pickup-Dunmur) chirality index.
        skipSymmetryAnalyzis (bool): If True, skips the symmetry analysis.
        skipFacetInfo (bool): If True, skips the external-facet info calculation.
        thresholdCoreSurface (float): Threshold used to distinguish core from
            surface atoms.

    Note:
        Updates self.NP, self.nAtoms and self.cog in place.
        Does not modify NP_B.

    Example:
        # Keep only the part of a cube that overlaps with a sphere
        AuCube.intersect(PtSphere, cogB=[0, 0, 0], mode='hull')
    """
    if not noOutput:
        centertxt(f"CSG intersect (mode={mode})", bgc="#cbcbcb", size="12",
                  fgc="b", weight="bold")

    if mode not in ('hull', 'atoms'):
        print(f"{bg.LIGHTYELLOWB}Warning: unknown mode '{mode}', "
              f"defaulting to 'hull'.{bg.OFF}")
        mode = 'hull'

    # --- Position and rotate B ---
    pos_B = NP_B.NP.get_positions().copy()
    cog_B = NP_B.NP.get_center_of_mass()
    pos_B = pos_B - cog_B              # center B at origin
    pos_B = _apply_rotB(pos_B, rotB)   # rotate around its own center
    if cogB is not None:
        cogB_ang = np.array(cogB) * 10.0  # nm → Å
        pos_B = pos_B + cogB_ang

    # --- Positions of A ---
    pos_A = self.NP.get_positions()
    n_total = len(pos_A)

    # --- Estimate Rnn_A ---
    Rnn_A = getattr(self, 'Rnn', None)
    if Rnn_A is None:
        from scipy.spatial import KDTree
        tree = KDTree(pos_A)
        dists, _ = tree.query(pos_A, k=2)
        Rnn_A = np.median(dists[:, 1])
        if not noOutput:
            print(f"  Rnn_A estimated: {Rnn_A:.3f} Å")
    cutoff = threshold * Rnn_A

    # --- Compute mask: atoms of A to KEEP ---
    if mode == 'hull':
        from scipy.spatial import ConvexHull, Delaunay, KDTree
        # Compute hull on surface atoms of B if available
        if hasattr(NP_B, 'surfaceAtoms') and NP_B.surfaceAtoms is not None:
            pos_B_hull = pos_B[NP_B.surfaceAtoms]
        else:
            pos_B_hull = pos_B
        hull_B = ConvexHull(pos_B_hull)
        delaunay_B = Delaunay(pos_B_hull[hull_B.vertices])
        # Atoms strictly inside hull
        inside_hull = delaunay_B.find_simplex(pos_A) >= 0
        # Also keep atoms within cutoff of any surface atom of B
        # — avoids losing atoms just outside the hull but close to surface
        tree_surf = KDTree(pos_B_hull)
        dists_to_surf, _ = tree_surf.query(pos_A)
        near_surface = dists_to_surf < cutoff
        keep_mask = inside_hull | near_surface

    else:  # mode == 'atoms'
        from scipy.spatial import KDTree
        Rnn_A = getattr(self, 'Rnn', None)
        if Rnn_A is None:
            tree = KDTree(pos_A)
            dists, _ = tree.query(pos_A, k=2)
            Rnn_A = np.median(dists[:, 1])
            if not noOutput:
                print(f"  Rnn_A estimated: {Rnn_A:.3f} Å")
        cutoff = threshold * Rnn_A
        tree_B = KDTree(pos_B)
        dists, _ = tree_B.query(pos_A)
        keep_mask = dists < cutoff

    # --- Safety checks ---
    n_to_keep = int(np.count_nonzero(keep_mask))

    if n_to_keep == 0:
        print(f"\n{bg.DARKREDB}ERROR: no atoms of A are inside B — "
              f"operation cancelled.{bg.OFF}")
        print(f"  Check cogB position and mode='{mode}'.")
        return

    if n_to_keep == n_total:
        print(f"{bg.LIGHTYELLOWB}Warning: all atoms of A are inside B — "
              f"nothing changed. Check cogB position.{bg.OFF}")
        return

    # --- Apply mask ---
    self.NP = self.NP[keep_mask]

    # --- Invalidate old truncation planes ---
    # After intersection, the original planes are no longer valid
    # since the shape has fundamentally changed
    self.trPlanes      = None
    self.trPlanes_Wulff = None
    self.trPlanes_opt   = None
    # --- Recenter at origin ---
    if recenter:
        self.NP.positions -= self.NP.get_center_of_mass()

    # --- Update attributes ---
    self.nAtoms = len(self.NP)
    self.cog    = self.NP.get_center_of_mass()
    self._flush_stale_data(shape_update="_intersect")
    self.is_optimized = False

    if not noOutput:
        n_removed = n_total - n_to_keep
        print(f"  {n_removed} atoms removed, {self.nAtoms} remaining.")

    # --- Resolve parameters ---
    if postAnalyzis is None:
        postAnalyzis = getattr(self, 'postAnalyzis', True)
    if skipChiralityCalculation is None:
        skipChiralityCalculation = getattr(self, 'skipChiralityCalculation', True)
    if skipSymmetryAnalyzis is None:
        skipSymmetryAnalyzis = getattr(self, 'skipSymmetryAnalyzis', True)
    if skipFacetInfo is None:
        skipFacetInfo = getattr(self, 'skipFacetInfo', True)
    if thresholdCoreSurface is None:
        thresholdCoreSurface = getattr(self, 'thresholdCoreSurface', 3.0)

    if postAnalyzis:
        self.propPostMake(
            skipChiralityCalculation = skipChiralityCalculation,
            skipSymmetryAnalyzis     = skipSymmetryAnalyzis,
            skipFacetInfo            = skipFacetInfo,
            thresholdCoreSurface     = thresholdCoreSurface,
            noOutput                 = noOutput,
            is_optimized             = False,
        )

def flush_inlay_with(self,
                    NP_B,
                    cogB: list = None,
                    rotB=None,
                    mode: str = 'hull',
                    threshold: float = 0.8,
                    recenter: bool=True,
                    noOutput: bool = False,
                    postAnalyzis: bool = None,
                    skipChiralityCalculation: bool = None,
                    skipSymmetryAnalyzis: bool = None,
                    skipFacetInfo: bool = None,
                    thresholdCoreSurface: float = None,
             ):
    """
    Merge self.NP (object A) with the part of NP_B that overlaps with self.NP.
    Atoms of B outside A are discarded. Overlapping atoms are deduplicated.

    This is equivalent to:
        1. Keep only the atoms of B that are inside A (intersection of B with A).
        2. Add them to A, removing overlap within threshold * Rnn.

    Two modes are available:
    - 'hull' : the overlap region is defined by the convex hull of A.
    - 'atoms': atoms of B closer than threshold * Rnn to any atom of A
               are considered overlapping and added.

    Args:
        self: pyNMBcore object (A). Modified in place.
        NP_B: pyNMBcore object (B). Only the part inside A is added.
        cogB (list): Position in nm where the center of mass of B is placed
            before the operation. Default is None (B used as-is).
        rotB: Rotation applied to B before the operation, around its own
            center of mass. Accepts three forms:
            - None (default): no rotation.
            - [ux, uy, uz, angle]: single rotation — axis [ux, uy, uz]
              (Cartesian) and angle in degrees.
            - {'axis': [ux, uy, uz], 'angle': angle}: same as above.
            - [{'axis': [...], 'angle': ...}, ...]: list of rotations
              applied sequentially in the given order.
        mode (str): 'hull' (default) or 'atoms'.
        threshold (float): Distance threshold in units of Rnn for overlap
            detection and deduplication. Default is 0.8.
        recenter (bool): If True, recenters self.NP on its center of mass
            after slicing (default). Set to False when calling applySlicing
            multiple times in sequence (e.g. applying the same pattern on
            all 6 faces of a cube) to avoid shifting the reference frame
            between calls. In that case, recenter manually once at the end:
            NP.NP.positions -= NP.NP.get_center_of_mass()
        noOutput (bool): If True, suppresses output. Default is False.
        postAnalyzis (bool): If True, prints additional NP information.
        skipChiralityCalculation (bool): If True, skips the calculation of
            the OPD (Osipov-Pickup-Dunmur) chirality index.
        skipSymmetryAnalyzis (bool): If True, skips the symmetry analysis.
        skipFacetInfo (bool): If True, skips the external-facet info calculation.
        thresholdCoreSurface (float): Threshold used to distinguish core from
            surface atoms.

    Note:
        Updates self.NP, self.nAtoms and self.cog in place.
        Does not modify NP_B.
        The chemical species of B atoms are preserved in the merged structure.

    Example:
        # Merge the part of an octahedron that fits inside a cube
        AuCube.union(PtOh, cogB=[0, 0, 0.95], mode='hull')
    """
    if not noOutput:
        centertxt(f"CSG flush inlay (mode={mode})", bgc="#cbcbcb", size="12",
                  fgc="b", weight="bold")

    if mode not in ('hull', 'atoms'):
        print(f"{bg.LIGHTYELLOWB}Warning: unknown mode '{mode}', "
              f"defaulting to 'hull'.{bg.OFF}")
        mode = 'hull'

    # --- Position and rotate B ---
    pos_B = NP_B.NP.get_positions().copy()
    cog_B = NP_B.NP.get_center_of_mass()
    pos_B = pos_B - cog_B              # center B at origin
    pos_B = _apply_rotB(pos_B, rotB)   # rotate around its own center
    if cogB is not None:
        cogB_ang = np.array(cogB) * 10.0  # nm → Å
        pos_B = pos_B + cogB_ang

    # --- Positions of A ---
    pos_A = self.NP.get_positions()
    n_total_A = len(pos_A)

    # --- Estimate Rnn_A ---
    Rnn_A = getattr(self, 'Rnn', None)
    if Rnn_A is None:
        from scipy.spatial import KDTree
        tree = KDTree(pos_A)
        dists, _ = tree.query(pos_A, k=2)
        Rnn_A = np.median(dists[:, 1])
        if not noOutput:
            print(f"  Rnn_A estimated: {Rnn_A:.3f} Å")
    cutoff = threshold * Rnn_A

    # --- Step 1: keep only atoms of B inside A ---
    if mode == 'hull':
        from scipy.spatial import ConvexHull, Delaunay, KDTree
        # Compute hull on surface atoms of A if available
        if hasattr(self, 'surfaceAtoms') and self.surfaceAtoms is not None:
            pos_A_hull = pos_A[self.surfaceAtoms]
        else:
            pos_A_hull = pos_A
        hull_A = ConvexHull(pos_A_hull)
        delaunay_A = Delaunay(pos_A_hull[hull_A.vertices])

        # Atoms of B strictly inside hull of A
        inside_hull = delaunay_A.find_simplex(pos_B) >= 0
        # Also keep atoms of B within cutoff of surface of A
        tree_surf_A = KDTree(pos_A_hull)
        dists_to_surf, _ = tree_surf_A.query(pos_B)
        near_surface = dists_to_surf < cutoff
        keep_B_mask = inside_hull | near_surface

    else:  # mode == 'atoms'
        from scipy.spatial import KDTree
        tree_A = KDTree(pos_A)
        dists_B, _ = tree_A.query(pos_B)
        keep_B_mask = dists_B < cutoff
        
    n_B_kept = int(np.count_nonzero(keep_B_mask))

    if n_B_kept == 0:
        print(f"{bg.LIGHTYELLOWB}Warning: no atoms of B are inside A — "
              f"nothing added. Check cogB position.{bg.OFF}")
        return

    if not noOutput:
        print(f"  {n_B_kept}/{len(pos_B)} atoms of B are inside A.")

    pos_B_kept = pos_B[keep_B_mask]
    NP_B_kept  = NP_B.NP[keep_B_mask]
    NP_B_kept.set_positions(pos_B_kept)

    # --- Step 2: remove atoms of A that overlap with kept B atoms ---
    from scipy.spatial import KDTree
    tree_B_kept = KDTree(pos_B_kept)
    dists_A, _  = tree_B_kept.query(pos_A)
    overlap_A_mask = dists_A < cutoff
    n_removed_A = int(np.count_nonzero(overlap_A_mask))

    if not noOutput:
        print(f"  {n_removed_A} atoms of A removed (overlap within "
              f"{threshold:.2f} * Rnn = {cutoff:.3f} Å).")

    self.NP = self.NP[~overlap_A_mask]

    # --- Step 3: merge A (without overlaps) + kept B atoms ---
    import ase
    merged = self.NP + NP_B_kept

    # --- Invalidate old truncation planes ---
    self.trPlanes       = None
    self.trPlanes_Wulff = None
    self.trPlanes_opt   = None

    # --- Update attributes ---
    self.NP       = merged
    if recenter:
        self.NP.positions -= self.NP.get_center_of_mass()

    self.nAtoms   = len(self.NP)
    self.cog      = self.NP.get_center_of_mass()
    self._flush_stale_data(shape_update="_union")
    self.is_optimized = False

    if not noOutput:
        print(f"  {self.nAtoms} total atoms after inlay.")

    # --- Resolve parameters ---
    if postAnalyzis is None:
        postAnalyzis = getattr(self, 'postAnalyzis', True)
    if skipChiralityCalculation is None:
        skipChiralityCalculation = getattr(self, 'skipChiralityCalculation', True)
    if skipSymmetryAnalyzis is None:
        skipSymmetryAnalyzis = getattr(self, 'skipSymmetryAnalyzis', True)
    if skipFacetInfo is None:
        skipFacetInfo = getattr(self, 'skipFacetInfo', True)
    if thresholdCoreSurface is None:
        thresholdCoreSurface = getattr(self, 'thresholdCoreSurface', 3.0)

    if postAnalyzis:
        self.propPostMake(
            skipChiralityCalculation = skipChiralityCalculation,
            skipSymmetryAnalyzis     = skipSymmetryAnalyzis,
            skipFacetInfo            = skipFacetInfo,
            thresholdCoreSurface     = thresholdCoreSurface,
            noOutput                 = noOutput,
            is_optimized             = False,
        )

def interface_distance_histogram(self, elemA, elemB, Rnn,
                                 overlap_frac=0.85, contact_frac=1.2,
                                 bins=60, is_optimized=None,
                                 save_path=None, noOutput=False):
    """
    Histogram of cross-species nearest-neighbour distances at the interface
    between two chemical species, to assess how cleanly two pieces were joined
    (e.g. after union_with on a bimetallic core/shell object) and to flag
    overlapping atoms produced by the merge.

    For every atom of species A the distance to its nearest atom of species B
    is computed (and vice-versa). The distribution should peak at the expected
    contact distance Rnn: a peak shifted BELOW Rnn means the two pieces
    interpenetrate (overlapping atoms), a peak shifted ABOVE means a gap.

    Args:
        self: pyNMBcore instance holding a bimetallic self.NP (or self.NP_opt).
        elemA, elemB (str): the two chemical symbols of the interface
            (e.g. 'Au', 'Ag').
        Rnn (float): expected first-neighbour contact distance in Å, drawn as
            the ideal-contact reference line.
        overlap_frac (float): atoms closer than overlap_frac*Rnn to the other
            species are counted as overlapping. Default 0.85.
        contact_frac (float): atoms within contact_frac*Rnn of the other
            species are counted as interface atoms. Default 1.2.
        bins (int): histogram bins. Default 60.
        is_optimized (bool or None): target structure. None -> self.is_optimized.
        save_path (str): if given, saves the figure (.png or .svg).
        noOutput (bool): if True, suppresses the printed summary. Default False.

    Returns:
        dict: {'d_A_to_B', 'd_B_to_A' (arrays, Å),
               'n_overlap', 'n_interface' (int),
               'd_min' (float, Å)}.
    """
    import numpy as np
    from scipy.spatial import cKDTree
    import matplotlib
    import matplotlib.pyplot as plt

    if is_optimized is None:
        is_optimized = getattr(self, 'is_optimized', False)
    use_opt = is_optimized and getattr(self, 'NP_opt', None) is not None
    atoms = self.NP_opt if use_opt else self.NP
    status = "optimized structure" if use_opt else "initial structure"

    pos  = atoms.get_positions()
    elem = np.array(atoms.get_chemical_symbols())
    A = pos[elem == elemA]
    B = pos[elem == elemB]
    if len(A) == 0 or len(B) == 0:
        raise ValueError(f"need both {elemA} ({len(A)}) and {elemB} "
                         f"({len(B)}) present in the structure.")

    d_A_to_B, _ = cKDTree(B).query(A, k=1)
    d_B_to_A, _ = cKDTree(A).query(B, k=1)
    d_all = np.concatenate([d_A_to_B, d_B_to_A])

    overlap_thr = overlap_frac * Rnn
    contact_thr = contact_frac * Rnn
    n_overlap   = int(np.count_nonzero(d_all < overlap_thr))
    n_interface = int(np.count_nonzero(d_all < contact_thr))
    d_min = float(d_all.min())

    # shared bin edges so both series have identical bar widths
    bin_edges = np.histogram_bin_edges(d_all, bins=bins)

    if not noOutput:
        centertxt(f"{elemA}/{elemB} interface analysis ({status})",
                  bgc='#007a7a', size='14', weight='bold')
        print(f" - Closest {elemA}-{elemB} distance : {d_min:.2f} Å")
        print(f" - Ideal contact (Rnn)        : {Rnn:.2f} Å")
        print(f" - Interface atoms (<{contact_frac:.1f}·Rnn) : {n_interface}")
        print(f" - Overlapping atoms (<{overlap_frac:.2f}·Rnn = "
              f"{overlap_thr:.2f} Å) : {n_overlap}")
        if n_overlap:
            print(f"   ⚠ {n_overlap} atoms interpenetrate — consider "
                  f"remove_duplicates() or a small gap before union_with().")

    fig, ax = plt.subplots(figsize=(9, 5.5))
    ax.hist(d_A_to_B, bins=bin_edges, alpha=0.6, color='#d4af37',
            edgecolor='black', label=f'{elemA} → nearest {elemB}')
    ax.hist(d_B_to_A, bins=bin_edges, alpha=0.6, color='#b0b0b0',
            edgecolor='black', label=f'{elemB} → nearest {elemA}')
    ax.axvline(Rnn, color='green', ls='--', lw=2, label='Rnn (ideal contact)')
    ax.axvline(overlap_thr, color='crimson', ls=':', lw=2,
               label=f'overlap < {overlap_thr:.2f} Å')
    ax.axvspan(0, overlap_thr, color='crimson', alpha=0.08)
    ax.set_xlabel('cross-species nearest-neighbour distance (Å)',
                  fontsize=13, fontweight='bold')
    ax.set_ylabel('number of atoms', fontsize=13, fontweight='bold')
    ax.set_title(f'{elemA}/{elemB} interface — {n_interface} interface atoms, '
                 f'{n_overlap} overlapping ({status})',
                 fontsize=13, fontweight='bold')
    ax.legend(prop={'weight': 'bold'})
    ax.grid(True, linestyle=':', alpha=0.5)
    ax.set_xlim(left=0)
    for tk in ax.get_xticklabels() + ax.get_yticklabels():
        tk.set_fontweight('bold')

    plt.tight_layout()
    if save_path:
        if save_path.lower().endswith('.svg'):
            matplotlib.rcParams['svg.fonttype'] = 'none'
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        if not noOutput:
            print(f" - Plot saved to: {save_path}")
    plt.show()

    return {'d_A_to_B': d_A_to_B, 'd_B_to_A': d_B_to_A,
            'n_overlap': n_overlap, 'n_interface': n_interface,
            'd_min': d_min}


######################################## systematic carve_by 

def _silhouette_ref_edge(pos_B, carve_axis):
    """
    Orthogonal projection of B's atoms along carve_axis → 2D convex hull
    (the silhouette). Returns the first silhouette edge as a 3D unit vector,
    used as B's azimuthal reference for coherent face alignment.
    """
    import numpy as np
    from scipy.spatial import ConvexHull
    u = np.asarray(carve_axis, float); u = u / np.linalg.norm(u)
    arb = np.array([1., 0, 0]) if abs(u[0]) < 0.9 else np.array([0, 1., 0])
    e1 = arb - (arb @ u) * u; e1 /= np.linalg.norm(e1)
    e2 = np.cross(u, e1)
    P = np.column_stack([pos_B @ e1, pos_B @ e2])
    hull = ConvexHull(P)
    poly = P[hull.vertices]
    edge = poly[1] - poly[0]
    edge3d = edge[0] * e1 + edge[1] * e2
    return edge3d / np.linalg.norm(edge3d)


def _faces_of_A(pos_A):
    """
    Convex hull of A, coplanar simplices grouped into faces. For each face,
    return its outward unit normal n, its distance D to the centre, its
    centroid, and a reference edge (first edge of its ordered vertex polygon)
    used to align the carving pattern coherently across faces.
    """
    import numpy as np
    from scipy.spatial import ConvexHull
    hull = ConvexHull(pos_A)
    faces = {}
    for simplex, eq in zip(hull.simplices, hull.equations):
        nrm = eq[:3] / np.linalg.norm(eq[:3])
        D = -eq[3] / np.linalg.norm(eq[:3])
        key = tuple(np.round(nrm, 3))
        faces.setdefault(key, {'n': nrm, 'D': D, 'verts': set()})
        faces[key]['verts'].update(simplex.tolist())
    out = []
    for f in faces.values():
        if f['D'] <= 0:
            continue
        V = pos_A[list(f['verts'])]
        c = V.mean(0)
        n = f['n']
        rel = V - c
        rel = rel - np.outer(rel @ n, n)
        a0 = rel[0] / np.linalg.norm(rel[0])
        b0 = np.cross(n, a0)
        ang = np.arctan2(rel @ b0, rel @ a0)
        Vs = V[np.argsort(ang)]
        ref_edge = Vs[1] - Vs[0]
        ref_edge /= np.linalg.norm(ref_edge)
        out.append({'n': n, 'D': f['D'], 'center': c, 'ref_edge': ref_edge})
    return out


def _symmetry_directions(pos_B, kind):
    """
    Candidate axis directions of B (from its hull centroid ~ origin) toward a
    vertex, an edge midpoint, or a face centroid, depending on `kind`. Returns
    None if B's convex hull is degenerate (flat/linear) or if the requested
    element type yields no usable (non-zero) direction.
    """
    import numpy as np
    from scipy.spatial import ConvexHull
    try:
        hb = ConvexHull(pos_B)
    except Exception:
        return None                              # degenerate B (flat/linear)
    c = pos_B.mean(0)
    if kind == 'vertex':
        dirs = pos_B[hb.vertices] - c
    elif kind == 'face':
        dirs = np.array([pos_B[s].mean(0) - c for s in hb.simplices])
    elif kind == 'edge':
        edges = set()
        for s in hb.simplices:
            for a, b in ((s[0], s[1]), (s[1], s[2]), (s[0], s[2])):
                edges.add((min(a, b), max(a, b)))
        dirs = np.array([0.5 * (pos_B[a] + pos_B[b]) - c for a, b in edges])
    else:
        raise ValueError("axis_through must be 'vertex', 'edge' or 'face'.")
    n = np.linalg.norm(dirs, axis=1, keepdims=True)
    good = (n > 1e-6).ravel()
    if not np.any(good):
        return None                              # all directions ill-defined
    return dirs[good] / n[good]


def _resolve_carve_axis(pos_B, carve_axis, axis_through, lead):
    """
    Resolve the carving axis (an axis OF B, in B's own frame, that will be
    aligned onto each face normal of A) and its SENSE so the chosen end of B
    leads the penetration. Returns (axis, fallback_msgs).

    Resolution when carve_axis is None:
      1. take B's `axis_through` directions ('vertex'|'edge'|'face'); among
         equivalents, pick the one best aligned with B's principal inertia
         axis (or the first, if B's inertia is isotropic);
      2. FALLBACK cascade if the requested type is geometrically ill-defined:
         try the other element types, then B's inertia axis, then [0,0,1];
      3. each fallback used is reported in fallback_msgs.

    Sense (`lead`): the sparser end of B along the axis is the 'apex' (a point),
    the denser end is the 'base' (a face). lead='apex' sends the apex inward;
    lead='base' sends the base inward. On an 'edge' axis the two ends are
    usually symmetric, so `lead` then has little effect.
    """
    import numpy as np
    msgs = []

    if carve_axis is None:
        order = {'edge':   ['edge', 'vertex', 'face'],
                 'vertex': ['vertex', 'edge', 'face'],
                 'face':   ['face', 'vertex', 'edge']}[axis_through]
        dirs, used = None, None
        for k in order:
            dirs = _symmetry_directions(pos_B, k)
            if dirs is not None:
                used = k
                break
        if dirs is None:
            # no usable element direction at all → inertia, then arbitrary
            try:
                cov = (pos_B.T @ pos_B) / len(pos_B)
                ev, evec = np.linalg.eigh(cov)
                if ev.max() - ev.min() > 1e-3 * ev.max():
                    msgs.append("no usable element direction on B → "
                                "fell back to its principal inertia axis.")
                    axis = evec[:, np.argmax(ev)]
                else:
                    raise ValueError
            except Exception:
                msgs.append("B is degenerate → fell back to arbitrary axis "
                            "[0,0,1].")
                axis = np.array([0, 0, 1.])
        else:
            if used != axis_through:
                msgs.append(f"axis_through='{axis_through}' ill-defined on B "
                            f"→ used '{used}' instead.")
            cov = (pos_B.T @ pos_B) / len(pos_B)
            ev, evec = np.linalg.eigh(cov)
            if ev.max() - ev.min() > 1e-3 * ev.max():
                axis = dirs[np.argmax(np.abs(dirs @ evec[:, np.argmax(ev)]))]
            else:
                axis = dirs[0]
    else:
        axis = np.asarray(carve_axis, float)
    axis = axis / np.linalg.norm(axis)

    proj = pos_B @ axis
    span = proj.max() - proj.min()
    tol = 0.02 * span if span > 0 else 1e-6
    n_hi = int(np.sum(proj > proj.max() - tol))
    n_lo = int(np.sum(proj < proj.min() + tol))
    apex_at_hi = n_hi <= n_lo
    if lead == 'apex':
        if apex_at_hi:
            axis = -axis
    elif lead == 'base':
        if not apex_at_hi:
            axis = -axis
    else:
        raise ValueError(f"lead must be 'apex' or 'base', got '{lead}'.")
    return axis, msgs


def _estimate_Rnn_local(coords):
    """Median nearest-neighbour distance of a point set (Å)."""
    import numpy as np
    from scipy.spatial import cKDTree
    if len(coords) < 2:
        return 0.0
    d, _ = cKDTree(coords).query(coords, k=2)
    return float(np.median(d[:, 1]))


def systematic_carve_by(self, NP_B, carve_axis=None, axis_through='vertex',
                        lead='apex', depth_nm=None, scale=1.0, phase_deg=0.0,
                        mode='hull', threshold=0.8,
                        preview=False, recenter=True,
                        noOutput=False, postAnalyzis=None,
                        skipChiralityCalculation=None, skipSymmetryAnalyzis=None,
                        skipFacetInfo=None, thresholdCoreSurface=None):
    """
    Systematically carve every face of self.NP (object A) with an arbitrary
    pyNMB object B used as the carving pattern (an "emporte-pièce"). For each
    face found on A's convex hull, an oriented, positioned copy of B is placed
    on the face and its volume is subtracted (CSG), hollowing a cavity in the
    shape of B.

    Because B is any pyNMB object, the whole library becomes a pattern bank.
    The cavity orientation is anchored on each face's first edge for inter-face
    coherence, plus a free phase_deg rotation, and is INDEPENDENT of the face
    shape — a triangular pit can be carved into a pentagonal face.

    Two carving modes:
      - mode='hull' (default): atoms of A inside the CONVEX HULL of the placed
        B are removed. Fast and geometrically exact, but B is reduced to its
        convex envelope — a concave B (cross, star, ring) carves its filled
        outline, not its true shape. `scale` is honoured here (the hull scales
        cleanly).
      - mode='atoms': atoms of A within threshold*Rnn of any atom of B are
        removed. Respects ANY shape of B, including concave ones, because it
        follows B's actual atoms. `scale` is IGNORED in this mode (scaling
        would space B's atoms apart and leave gaps) — build B at the target
        size instead.

    After carving, the shape is non-convex: use coreSurfaceMethod='cnp' or
    'combined' for a correct core/surface classification of the result.

    Args:
        self: pyNMBcore object (A). Modified in place (unless preview=True).
        NP_B: pyNMBcore object (B). The carving pattern. Never modified.
        carve_axis (array-like or None): an axis OF B, expressed in B's OWN
            frame, that gets aligned onto each face normal of A — so it becomes
            the direction along which B sinks into that face. None (default)
            picks it automatically from `axis_through` (see below). A given
            vector is taken in B's frame and overrides axis_through; its sense
            is still set by `lead`.
        axis_through (str): when carve_axis is None, which symmetry direction of
            B (in B's frame) becomes the penetration axis: 'vertex' (default)
            drives B vertex-first (a pointed pit), 'edge' edge-first (a
            wedge/dihedral pit), 'face' face-first (a flat-bottomed pit). Among
            equivalent directions, the one best aligned with B's principal
            inertia axis is chosen (or the first, if B's inertia is isotropic).
            If the requested type is geometrically ill-defined for B (e.g.
            'edge' on a near-sphere) or B's hull is degenerate (flat/linear),
            a fallback cascade is used (other element types, then B's inertia
            axis, then [0,0,1]) and a Note is printed.
        lead (str): which end of B leads the penetration. 'apex' (default): the
            sparser, pointed end enters first; 'base': the denser, flat end.
            Has little effect on an 'edge' axis (its two ends are symmetric).
        depth_nm (float or None): SIGNED distance, in nm, between B's leading
            (inner) tip and A's centre of gravity, along the inward normal. 0
            puts the inner tip at A's centre; positive keeps it between surface
            and centre (shallower); negative pushes it past the centre
            (through-cavities). None (default) = half-way to the centre.
        scale (float): scale factor applied to B. Honoured in mode='hull',
            IGNORED in mode='atoms'. Default 1.0.
        phase_deg (float): extra azimuthal rotation of B about the face normal.
        mode (str): 'hull' (default) or 'atoms'. See above.
        threshold (float): mode='atoms' only — atoms of A within threshold*Rnn
            of any atom of B are removed. Rnn is the larger of A's and B's
            nearest-neighbour distances, so the capture stays gap-free.
            Default 0.8.
        preview (bool): if True, DO NOT carve. In mode='hull', build
            self.NP_preview = A alone (real species) and set self.jMolCarvePreview
            (via external_pgm.defCarvePreviewForJMol) to a Jmol command drawing
            each placed B's hull as translucent polygons — the exact removed
            volume, clear even when scale > 1 (no marker atoms, which would only
            clutter the view). In mode='atoms', build self.NP_preview = A +
            placed copies of B as marker 'No' atoms (whose large radius keeps
            them bonded in Jmol) tracing B's true, possibly concave shape, and
            set self.jMolCarvePreview = None. self.NP is left untouched in both
            cases.
        recenter (bool): recentre on the COM after carving. Default True.
        noOutput (bool): suppress output. Default False.
        postAnalyzis, skip*: standard post-analysis controls (None -> self.*).

    Returns:
        None. Updates self.NP in place, or self.NP_preview if preview=True.

    Example:
        # Convex pattern (tetrahedron), hull mode, scale honoured
        octa.systematic_carve_by(td, depth_nm=0.0, scale=2, lead='apex')

        # Concave pattern (a cross), atoms mode, build B at target size
        cross = pNP.... # a cross-shaped pyNMB object at the right size
        cube.systematic_carve_by(cross, depth_nm=0.0, mode='atoms')

        # Preview either before committing
        octa.systematic_carve_by(td, depth_nm=0.0, scale=2, preview=True)
        pyNMBu.write("coords/preview.xyz", octa.NP_preview)
    """
    import numpy as np
    from scipy.spatial import ConvexHull, Delaunay, cKDTree
    from scipy.spatial.transform import Rotation
    from ase import Atoms

    if mode not in ('hull', 'atoms'):
        raise ValueError(f"mode must be 'hull' or 'atoms', got '{mode}'.")

    if not noOutput:
        title = ("Preview: carving pattern placement"
                 if preview else "Systematic face carving by a pattern object")
        centertxt(title, bgc='#007a7a', size='14', weight='bold')
        chrono = timer(); chrono.chrono_start()

    # --- source structure of A -------------------------------------------
    if self.is_optimized and getattr(self, 'NP_opt', None) is not None:
        target_atoms = self.NP_opt
        status = "optimized structure"
    else:
        target_atoms = self.NP
        status = "initial structure"
    pos_A = target_atoms.get_positions()
    cog_A = target_atoms.get_center_of_mass()
    pos_A_c = pos_A - cog_A                       # A centred: cog at origin

    # --- scale handling depends on mode ----------------------------------
    eff_scale = float(scale)
    if mode == 'atoms' and abs(eff_scale - 1.0) > 1e-9:
        if not noOutput:
            print(f"{bg.LIGHTYELLOWB}Warning: scale is ignored in "
                  f"mode='atoms' (scaling would space B's atoms apart and "
                  f"leave gaps). Build B at the target size. Using "
                  f"scale=1.{bg.OFF}")
        eff_scale = 1.0

    # --- pattern B: centred, scaled --------------------------------------
    pos_B = NP_B.NP.get_positions().copy()
    pos_B = pos_B - pos_B.mean(0)
    pos_B = pos_B * eff_scale

    carve_axis, axis_msgs = _resolve_carve_axis(pos_B, carve_axis,
                                                axis_through, lead)
    if axis_msgs and not noOutput:
        for m in axis_msgs:
            print(f"{bg.LIGHTYELLOWB}Note: {m}{bg.OFF}")
    ref_edge_B = _silhouette_ref_edge(pos_B, carve_axis)

    # capture radius for mode='atoms' (larger of A's and B's Rnn)
    if mode == 'atoms':
        Rnn_A = getattr(self, 'Rnn', None) or _estimate_Rnn_local(pos_A_c)
        Rnn_B = _estimate_Rnn_local(pos_B)
        cutoff = threshold * max(Rnn_A, Rnn_B)

    # depth: inner (leading) tip relative to A's cog
    if depth_nm is None:
        faces_tmp = _faces_of_A(pos_A_c)
        Dmin = min(f['D'] for f in faces_tmp) if faces_tmp else 0.0
        depth_ang = 0.5 * Dmin
    else:
        depth_ang = depth_nm * 10.0              # nm -> Å (signed)

    # --- faces of A -------------------------------------------------------
    faces = _faces_of_A(pos_A_c)
    if len(faces) == 0:
        if not noOutput:
            print("  No faces found — nothing to do.")
        return

    phase = float(phase_deg)
    B_copies = []
    remove = np.zeros(len(pos_A_c), dtype=bool)

    for f in faces:
        R, _ = Rotation.align_vectors(
            np.array([f['n'], f['ref_edge']]),
            np.array([carve_axis, ref_edge_B]))
        Bp = (R.as_matrix() @ pos_B.T).T
        if phase != 0.0:
            Rp = Rotation.from_rotvec(np.radians(phase) * f['n']).as_matrix()
            Bp = (Rp @ Bp.T).T
        proj = Bp @ f['n']
        inner = proj.min()
        Bp = Bp + (depth_ang - inner) * f['n']

        if preview:
            B_copies.append(Bp.copy())
            continue

        if mode == 'hull':
            try:
                hb = ConvexHull(Bp)
                dl = Delaunay(Bp[hb.vertices])
                remove |= dl.find_simplex(pos_A_c) >= 0
            except Exception:
                continue
        else:  # mode == 'atoms'
            d, _ = cKDTree(Bp).query(pos_A_c)
            remove |= d < cutoff

    # --- preview branch ---------------------------------------------------
    if preview:
        symbols_A = target_atoms.get_chemical_symbols()
        if mode == 'hull':
            # hull mode: the translucent polygons show the exact carving
            # volume — clean even when scale > 1. Adding 'No' atoms would only
            # clutter the view (and they spread apart with scale), so
            # NP_preview holds A alone and the patterns live in the script.
            self.NP_preview = Atoms(symbols=list(symbols_A), positions=pos_A_c)
            from .external_pgm import defCarvePreviewForJMol
            self.jMolCarvePreview = defCarvePreviewForJMol(
                self, B_copies, color="xff3030", noOutput=True)
        else:
            # atoms mode: the 'No' marker atoms ARE the representation — they
            # trace B's true (possibly concave) shape. No polygons.
            all_pos = [pos_A_c]
            all_sym = list(symbols_A)
            for Bp in B_copies:
                all_pos.append(Bp)
                all_sym += ['No'] * len(Bp)     # No: large radius, bonds shown
            self.NP_preview = Atoms(symbols=all_sym,
                                    positions=np.vstack(all_pos))
            self.jMolCarvePreview = None
        if not noOutput:
            print(f"  - Source        : {status}")
            print(f"  - Mode          : '{mode}'")
            print(f"  - Faces         : {len(faces)} "
                  f"({len(B_copies)} pattern copies placed)")
            print(f"  - carve_axis    : [{carve_axis[0]:+.3f} "
                  f"{carve_axis[1]:+.3f} {carve_axis[2]:+.3f}]  lead='{lead}'")
            print(f"  - Inner tip at  : {depth_ang/10:.2f} nm from cog")
            if mode == 'hull':
                print(f"  - Stored as     : self.NP_preview (A only) and "
                      f"self.jMolCarvePreview (pattern hull outlines).")
                print(f"    self.NP untouched. To inspect in Jmol:")
                print(f"      pyNMBu.write('preview.xyz', NP.NP_preview)")
                print(f"      pyNMBu.write('preview.script', "
                      f"NP.jMolCarvePreview)")
                print(f"      then in Jmol, load preview.xyz and run: "
                      f"script './preview.script'")
            else:
                print(f"  - Stored as     : self.NP_preview (A + B as 'No', "
                      f"showing B's true shape). No hull outline in atoms mode.")
                print(f"    self.NP untouched. To inspect in Jmol:")
                print(f"      pyNMBu.write('preview.xyz', NP.NP_preview)")
            chrono.chrono_stop(hdelay=False); chrono.chrono_show()
        return

    # --- carving branch ---------------------------------------------------
    keep = ~remove
    old_count = len(pos_A_c)
    n_removed = int(np.count_nonzero(remove))

    if n_removed == 0 and not noOutput:
        print(f"{bg.LIGHTYELLOWB}Warning: no atoms carved — check depth_nm, "
              f"scale, lead, mode, or carve_axis (B may not reach into "
              f"A).{bg.OFF}")
    if n_removed == old_count:
        print(f"{bg.DARKREDB}ERROR: all atoms would be removed — operation "
              f"cancelled. Reduce scale/threshold or adjust depth_nm.{bg.OFF}")
        return

    symbols = target_atoms.get_chemical_symbols()
    self.NP = Atoms(symbols=[symbols[i] for i in np.where(keep)[0]],
                    positions=pos_A[keep])
    if recenter and len(self.NP) > 0:
        self.NP.positions -= self.NP.get_center_of_mass()
    self.nAtoms = len(self.NP)
    self.cog = self.NP.get_center_of_mass()

    self.trPlanes = None
    self.trPlanes_Wulff = None
    self.trPlanes_opt = None

    if not noOutput:
        print(f"  - Source        : {status}")
        print(f"  - Mode          : '{mode}'"
              + (f" (scale {eff_scale:.2f})" if mode == 'hull'
                 else f" (threshold {threshold:.2f}·Rnn = {cutoff:.2f} Å)"))
        print(f"  - Pattern B     : {len(pos_B)} atoms")
        print(f"  - carve_axis    : [{carve_axis[0]:+.3f} {carve_axis[1]:+.3f} "
              f"{carve_axis[2]:+.3f}]  lead='{lead}'")
        print(f"  - Faces carved  : {len(faces)}")
        print(f"  - Inner tip at  : {depth_ang/10:.2f} nm from cog, "
              f"phase {phase:.0f}°")
        print(f"  - Atoms removed : {n_removed} "
              f"({100*n_removed/old_count:.0f} %)")
        print(f"  - {self.nAtoms} atoms remaining. self.NP updated.")
        print(f"  Tip: the result is concave — use coreSurfaceMethod='cnp' "
              f"or 'combined' for a correct core/surface split.")
        chrono.chrono_stop(hdelay=False); chrono.chrono_show()

    self._flush_stale_data(shape_update="_systematic_carve")
    self.is_optimized = False

    if postAnalyzis is None:
        postAnalyzis = getattr(self, 'postAnalyzis', True)
    if skipChiralityCalculation is None:
        skipChiralityCalculation = getattr(self, 'skipChiralityCalculation', True)
    if skipSymmetryAnalyzis is None:
        skipSymmetryAnalyzis = getattr(self, 'skipSymmetryAnalyzis', True)
    if skipFacetInfo is None:
        skipFacetInfo = getattr(self, 'skipFacetInfo', True)
    if thresholdCoreSurface is None:
        thresholdCoreSurface = getattr(self, 'thresholdCoreSurface', 3.0)
    if postAnalyzis and self.nAtoms > 0:
        self.propPostMake(
            skipChiralityCalculation=skipChiralityCalculation,
            skipSymmetryAnalyzis=skipSymmetryAnalyzis,
            skipFacetInfo=skipFacetInfo,
            thresholdCoreSurface=thresholdCoreSurface,
            noOutput=noOutput, is_optimized=False)

###############################################################

def systematic_stellate_by(self, NP_B, carve_axis=None, axis_through='vertex',
                           lead='base', depth_nm=None, seat_on_face=True,
                           scale=1.0, phase_deg=0.0, mode='hull', threshold=0.8,
                           preview=False, recenter=True,
                           noOutput=False, postAnalyzis=None,
                           skipChiralityCalculation=None, skipSymmetryAnalyzis=None,
                           skipFacetInfo=None, thresholdCoreSurface=None):
    """
    Systematically raise a relief on every face of self.NP (object A) by ADDING
    an arbitrary pyNMB object B on each face (the additive counterpart of
    systematic_carve_by). For each face of A's convex hull, an oriented,
    positioned copy of B is merged onto the face with union_with, growing a
    point/relief outward — producing stellation-like and studded morphologies.

    This is the "+" sibling of systematic_carve_by (which subtracts). Both share
    the same placement machinery (axis_through, lead, depth_nm/seat_on_face,
    scale, phase_deg); only the boolean operation differs: stellate UNIONS B,
    carve SUBTRACTS it. The lattice of B is generally NOT registered with A, so
    each raised piece joins A through an interface (assumed, cleaned by
    union_with's overlap removal) — fine for a geometric object.

    Args:
        self: pyNMBcore object (A). Modified in place (unless preview=True).
        NP_B: pyNMBcore object (B). The relief pattern. Never modified.
        carve_axis (array-like or None): an axis OF B, in B's own frame, aligned
            onto each face normal of A. None (default) → derived from
            axis_through. A given vector overrides axis_through; its sense is
            still set by `lead`.
        axis_through (str): when carve_axis is None, which symmetry direction of
            B becomes the penetration axis: 'vertex' (default), 'edge' or 'face'.
        lead (str): which end of B leads (goes inward, toward A's core). For a
            stellation you usually want the BASE seated on the face and the apex
            pointing OUT, so the default here is 'base' (note: differs from
            carve's 'apex' default). 'apex' would sink the point into A instead.
        depth_nm (float or None): SIGNED distance (nm) between B's leading inner
            tip and A's centre of gravity, along the inward normal. Same
            convention as systematic_carve_by. Ignored when seat_on_face=True.
            None places the tip half-way to the centre.
        seat_on_face (bool): if True (default), ignore depth_nm and seat B's
            leading end exactly on each face plane, so B sits on the surface and
            protrudes outward (the natural stellation placement). Set False to
            control the position manually with depth_nm.
        scale (float): scale factor applied to B. Honoured in mode='hull',
            ignored in mode='atoms'. Default 1.0.
        phase_deg (float): azimuthal rotation of B about the face normal, deg.
        mode (str): passed to union_with — 'hull' (default) or 'atoms'.
        threshold (float): passed to union_with — atoms of A within
            threshold*Rnn of B are removed before merging. Default 0.8.
        preview (bool): if True, DO NOT add. In mode='hull', build
            self.NP_preview = A alone and set self.jMolStellationPreview (via
            external_pgm.defCarvePreviewForJMol) to a Jmol command drawing
            each placed B's hull as translucent polygons (the exact relief
            volume, clear even when scale > 1). In mode='atoms', build
            self.NP_preview = A + placed copies of B as marker 'No' atoms
            (tracing B's true, possibly concave shape) and set
            self.jMolStellationPreview = None. self.NP is left untouched in both
            cases.
        recenter (bool): recentre on the COM once at the end. Default True.
        noOutput (bool): suppress output. Default False.
        postAnalyzis, skip*: standard post-analysis controls (None -> self.*).

    Returns:
        None. Updates self.NP in place (via union_with per face), or
        self.NP_preview if preview=True.

    Example:
        # Small-triambic-like relief: a low tetrahedron raised point-out on
        # every face of an icosahedron
        ico.systematic_stellate_by(td, axis_through='vertex', lead='base',
                                   seat_on_face=True, scale=1.0)
    """
    import numpy as np
    from scipy.spatial.transform import Rotation
    from ase import Atoms

    if mode not in ('hull', 'atoms'):
        raise ValueError(f"mode must be 'hull' or 'atoms', got '{mode}'.")

    if not noOutput:
        title = ("Preview: stellation pattern placement"
                 if preview else "Systematic face stellation by a pattern object")
        centertxt(title, bgc='#007a7a', size='14', weight='bold')
        chrono = timer(); chrono.chrono_start()

    # --- source structure of A -------------------------------------------
    if self.is_optimized and getattr(self, 'NP_opt', None) is not None:
        target_atoms = self.NP_opt
        status = "optimized structure"
    else:
        target_atoms = self.NP
        status = "initial structure"
    pos_A = target_atoms.get_positions()
    cog_A = target_atoms.get_center_of_mass()
    pos_A_c = pos_A - cog_A                       # A centred: cog at origin

    # --- scale handling (same rule as carve) -----------------------------
    eff_scale = float(scale)
    if mode == 'atoms' and abs(eff_scale - 1.0) > 1e-9:
        if not noOutput:
            print(f"{bg.LIGHTYELLOWB}Warning: scale is ignored in "
                  f"mode='atoms'. Build B at the target size. Using "
                  f"scale=1.{bg.OFF}")
        eff_scale = 1.0

    # --- pattern B: centred, scaled --------------------------------------
    pos_B = NP_B.NP.get_positions().copy()
    pos_B = pos_B - pos_B.mean(0)
    pos_B = pos_B * eff_scale

    carve_axis, axis_msgs = _resolve_carve_axis(pos_B, carve_axis,
                                                axis_through, lead)
    if axis_msgs and not noOutput:
        for m in axis_msgs:
            print(f"{bg.LIGHTYELLOWB}Note: {m}{bg.OFF}")
    ref_edge_B = _silhouette_ref_edge(pos_B, carve_axis)

    # --- faces of A -------------------------------------------------------
    faces = _faces_of_A(pos_A_c)
    if len(faces) == 0:
        if not noOutput:
            print("  No faces found — nothing to do.")
        return

    # default depth (only used when seat_on_face is False)
    if depth_nm is None:
        Dmin = min(f['D'] for f in faces) if faces else 0.0
        depth_ang_default = 0.5 * Dmin
    else:
        depth_ang_default = depth_nm * 10.0

    phase = float(phase_deg)

    # --- per face: compute rotB (axis-angle) and cogB (nm) ----------------
    # We reproduce union_with's internal placement exactly:
    #   union_with does pos_B_centered -> rotate(rotB) -> + cogB_ang
    # So rotB must be the same rotation R we use here, and cogB the final
    # centre of the placed (rotated) B.
    placements = []          # list of (rotB, cogB_nm)
    B_copies = []            # for preview only
    for f in faces:
        R, _ = Rotation.align_vectors(
            np.array([f['n'], f['ref_edge']]),
            np.array([carve_axis, ref_edge_B]))
        Rmat = R.as_matrix()
        Bp = (Rmat @ pos_B.T).T
        if phase != 0.0:
            Rp = Rotation.from_rotvec(np.radians(phase) * f['n']).as_matrix()
            Bp = (Rp @ Bp.T).T
            Rmat = Rp @ Rmat            # fold phase into the rotation

        # leading (inner) tip along the outward normal
        proj = Bp @ f['n']
        inner = proj.min()
        if seat_on_face:
            depth_ang = f['D']          # seat leading tip on this face's plane
        else:
            depth_ang = depth_ang_default
        Bp = Bp + (depth_ang - inner) * f['n']

        # express as rotB (axis-angle, B's own frame) + cogB (nm)
        rotvec = Rotation.from_matrix(Rmat).as_rotvec()
        ang = float(np.degrees(np.linalg.norm(rotvec)))
        if np.linalg.norm(rotvec) > 1e-12:
            ax = rotvec / np.linalg.norm(rotvec)
        else:
            ax = np.array([0.0, 0.0, 1.0])
        rotB = [float(ax[0]), float(ax[1]), float(ax[2]), ang]
        # cogB: union_with works in A's ORIGINAL (un-centred) frame, so add
        # cog_A back; cogB is given in nm.
        cogB_nm = ((Bp.mean(0) + cog_A) / 10.0).tolist()

        placements.append((rotB, cogB_nm))
        B_copies.append(Bp.copy())

    # --- preview branch ---------------------------------------------------
    if preview:
        symbols_A = target_atoms.get_chemical_symbols()
        seat_str = ("seated on each face" if seat_on_face
                    else f"inner tip {depth_ang_default/10:.2f} nm from cog")
        if mode == 'hull':
            # hull mode: the translucent polygons show the exact relief volume,
            # clean even when scale > 1. NP_preview holds A alone; the patterns
            # live in the Jmol script.
            self.NP_preview = Atoms(symbols=list(symbols_A), positions=pos_A_c)
            from .external_pgm import defCarvePreviewForJMol
            self.jMolStellationPreview = defCarvePreviewForJMol(
                self, B_copies, color="x2a75ff", noOutput=True)
        else:
            # atoms mode: the 'No' marker atoms trace B's true (possibly
            # concave) shape. No polygons.
            all_pos = [pos_A_c]
            all_sym = list(symbols_A)
            for Bp in B_copies:
                all_pos.append(Bp)
                all_sym += ['No'] * len(Bp)     # No: large radius, bonds shown
            self.NP_preview = Atoms(symbols=all_sym,
                                    positions=np.vstack(all_pos))
            self.jMolStellationPreview = None
        if not noOutput:
            print(f"  - Source        : {status}")
            print(f"  - Mode          : '{mode}'")
            print(f"  - Faces         : {len(faces)} "
                  f"({len(B_copies)} pattern copies placed)")
            print(f"  - carve_axis    : [{carve_axis[0]:+.3f} "
                  f"{carve_axis[1]:+.3f} {carve_axis[2]:+.3f}]  lead='{lead}'")
            print(f"  - Placement     : {seat_str}")
            if mode == 'hull':
                print(f"  - Stored as     : self.NP_preview (A only) and "
                      f"self.jMolStellationPreview (pattern hull outlines).")
                print(f"    self.NP untouched. To inspect in Jmol:")
                print(f"      pyNMBu.write('preview.xyz', NP.NP_preview)")
                print(f"      pyNMBu.write('preview.script', "
                      f"NP.jMolStellationPreview)")
                print(f"      then in Jmol, load preview.xyz and run: "
                      f"script './preview.script'")
            else:
                print(f"  - Stored as     : self.NP_preview (A + B as 'No', "
                      f"showing B's true shape). No hull outline in atoms mode.")
                print(f"    self.NP untouched. To inspect in Jmol:")
                print(f"      pyNMBu.write('preview.xyz', NP.NP_preview)")
            chrono.chrono_stop(hdelay=False); chrono.chrono_show()
        return

    # --- merge branch: one union_with per face, no recenter between -------
    n_before = len(target_atoms)
    for i, (rotB, cogB_nm) in enumerate(placements):
        self.union_with(
            NP_B, cogB=cogB_nm, rotB=rotB, mode=mode, threshold=threshold,
            recenter=False, noOutput=True, postAnalyzis=False)

    # recenter once at the end (as union_with's docstring recommends for
    # sequential face-by-face application)
    if recenter and len(self.NP) > 0:
        self.NP.positions -= self.NP.get_center_of_mass()
    self.nAtoms = len(self.NP)
    self.cog = self.NP.get_center_of_mass()

    self.trPlanes = None
    self.trPlanes_Wulff = None
    self.trPlanes_opt = None

    if not noOutput:
        n_added = self.nAtoms - n_before
        print(f"  - Source        : {status}")
        print(f"  - Mode          : '{mode}'"
              + (f" (scale {eff_scale:.2f})" if mode == 'hull' else ""))
        print(f"  - Pattern B     : {len(pos_B)} atoms")
        print(f"  - carve_axis    : [{carve_axis[0]:+.3f} {carve_axis[1]:+.3f} "
              f"{carve_axis[2]:+.3f}]  lead='{lead}'")
        print(f"  - Faces raised  : {len(faces)}")
        seat_str = ("seated on each face" if seat_on_face
                    else f"inner tip {depth_ang_default/10:.2f} nm from cog")
        print(f"  - Placement     : {seat_str}, phase {phase:.0f}°")
        print(f"  - Net atoms added: {n_added} "
              f"({n_before} -> {self.nAtoms})")
        print(f"  - self.NP updated.")
        chrono.chrono_stop(hdelay=False); chrono.chrono_show()

    self._flush_stale_data(shape_update="_systematic_stellate")
    self.is_optimized = False

    if postAnalyzis is None:
        postAnalyzis = getattr(self, 'postAnalyzis', True)
    if skipChiralityCalculation is None:
        skipChiralityCalculation = getattr(self, 'skipChiralityCalculation', True)
    if skipSymmetryAnalyzis is None:
        skipSymmetryAnalyzis = getattr(self, 'skipSymmetryAnalyzis', True)
    if skipFacetInfo is None:
        skipFacetInfo = getattr(self, 'skipFacetInfo', True)
    if thresholdCoreSurface is None:
        thresholdCoreSurface = getattr(self, 'thresholdCoreSurface', 3.0)
    if postAnalyzis and self.nAtoms > 0:
        self.propPostMake(
            skipChiralityCalculation=skipChiralityCalculation,
            skipSymmetryAnalyzis=skipSymmetryAnalyzis,
            skipFacetInfo=skipFacetInfo,
            thresholdCoreSurface=thresholdCoreSurface,
            noOutput=noOutput, is_optimized=False)