import time, datetime

import numpy as np

from .core import (pyNMB_location, get_resource_path, timer, RAB, Rbetween2Points,
                   vector, vectorBetween2Points, coord2xyz, vertex, vertexScaled, RadiusSphereAfterV,
                   centerOfGravity, center2cog, normOfV, normV, centerToVertices, Rx, Ry, Rz,
                   EulerRotationMatrix, plotPalette, rgb2hex, clone, deleteElementsOfAList,
                   planeFittingLSF, faces_to_planes, AngleBetweenVV, signedAngleBetweenVV
                   )
from .core import centertxt, centerTitle, fg, bg, hl, color
from .geometry import truncateAbovePlanes, setdAsNegative, rotationMolAroundAxis
#==================================================================================
#                          Constructive solid geometry
#==================================================================================

def applyTruncation(self,
                    planes,
                    distance_unit: str = 'nm',
                    noOutput: bool = False):
    """
    Apply one or more truncation planes to self.NP, with optional rotational
    symmetry generation. Works on any pyNMBcore object.

    Each plane is defined by a dictionary with the following keys:

    Plane definition (one of):
        'normal' (array-like): Plane normal as a Cartesian vector [u, v, w]
            (if normal_def='cart', default) or Miller indices [h, k, l]
            (if normal_def='hkl', requires self.Gstar — Crystal objects only).
        'angle' (float): Angle in degrees between the plane normal and the
            rotation axis (rotAxis). The reference normal is built by rotating
            rotAxis by this angle around an arbitrary perpendicular direction.

    Mandatory keys:
        'distance' (float): Distance from the origin (center of mass) to the
            truncation plane, in nm (default) or Å (if distance_unit='Angstrom').
        'side' (str): Which atoms to remove. 'above' removes atoms on the
            positive side of the plane normal (default). 'below' removes atoms
            on the negative side.

    Optional keys:
        'normal_def' (str): Coordinate system for 'normal'. Either 'cart'
            (Cartesian, default) or 'hkl' (Miller indices, Crystal only).
        'nRot' (int): Number of planes generated by rotation around rotAxis.
            angle = 360° / nRot. Default is 1 (no rotation symmetry).
        'rotAxis' (array-like): Rotation axis for symmetry generation, as a
            Cartesian vector. Required if nRot > 1.

    Args:
        planes (list of dict): List of plane definitions (see above).
        distance_unit (str): Unit for distances. 'nm' (default) or 'Angstrom'.
        noOutput (bool): If True, suppresses output. Default is False.

    Note:
        Updates self.NP, self.nAtoms and self.cog in place.
        self.trPlanes is updated with all applied truncation planes.
        self.trPlanes_Wulff is set to None (this is not a Wulff construction).

    Example:
        NP.applyTruncation(
            planes=[
                {'normal': [1, 1, 6], 'distance': 5.0,
                 'nRot': 6, 'rotAxis': [0, 0, 1], 'side': 'above'},
                {'normal': [0, 0, 1], 'distance': 3.0, 'side': 'below'},
                {'angle': 30.0, 'distance': 5.0,
                 'nRot': 4, 'rotAxis': [1, 0, 0], 'side': 'above'},
            ],
            distance_unit='nm',
        )
    """
    if not noOutput:
        centertxt("Custom truncation", bgc="#cbcbcb", size="12",
                  fgc="b", weight="bold")

    # --- Unit conversion ---
    scale = 10.0 if distance_unit == 'nm' else 1.0  # nm→Å

    all_tr_planes = []

    for plane_def in planes:

        # --- Get distance ---
        distance_ang = plane_def['distance'] * scale

        # --- Get side ---
        side = plane_def.get('side', 'above')
        if side not in ('above', 'below'):
            print(f"{bg.LIGHTYELLOWB}Warning: unknown side '{side}', "
                  f"defaulting to 'above'.{bg.OFF}")
            side = 'above'
        del_above = (side == 'above')

        # --- Build reference normal in Cartesian ---
        if 'normal' in plane_def:
            normal_def = plane_def.get('normal_def', 'cart')
            n = np.array(plane_def['normal'], dtype=float)
            if normal_def == 'hkl':
                if not hasattr(self, 'Gstar'):
                    raise AttributeError(
                        "normal_def='hkl' requires a Crystal object with "
                        "self.Gstar. Use normal_def='cart' instead.")
                from .crystals import lattice_cart
                n = lattice_cart(self, [n], Bravais2cart=True)[0]
            n = n / np.linalg.norm(n)

        elif 'angle' in plane_def:
            rot_axis = np.array(plane_def['rotAxis'], dtype=float)
            rot_axis = rot_axis / np.linalg.norm(rot_axis)
            angle_deg = plane_def['angle']
            # Build arbitrary perpendicular to rotAxis
            arbitrary = np.array([1, 0, 0]) if abs(rot_axis[0]) < 0.9 \
                        else np.array([0, 1, 0])
            perp = np.cross(rot_axis, arbitrary)
            perp = perp / np.linalg.norm(perp)
            # Rotate perp by angle around rotAxis
            n = rotationMolAroundAxis(perp, angle_deg, rot_axis)
            n = n / np.linalg.norm(n)
        else:
            raise ValueError(
                "Each plane definition must contain either 'normal' or 'angle'.")

        # --- Generate rotational family ---
        nRot = plane_def.get('nRot', 1)
        if nRot < 1:
            print(f"{bg.LIGHTYELLOWB}Warning: nRot={nRot} is invalid, set to 1.{bg.OFF}")
            nRot = 1

        if nRot > 1:
            rot_axis = np.array(plane_def['rotAxis'], dtype=float)
            rot_axis = rot_axis / np.linalg.norm(rot_axis)
            normals = [rotationMolAroundAxis(n, i * 360.0 / nRot, rot_axis)
                       for i in range(nRot)]
        else:
            normals = [n]

        # --- Build plane equations [nx, ny, nz, d] ---
        for nn in normals:
            nn = nn / np.linalg.norm(nn)
            all_tr_planes.append(np.append(nn, -distance_ang))

            if not noOutput:
                print(f"  Plane normal: [{nn[0]:+.4f} {nn[1]:+.4f} {nn[2]:+.4f}]"
                      f"  d = {-distance_ang:.3f} Å  side = {side}")

    atoms_to_del = truncateAbovePlanes(
        all_tr_planes,
        self.NP.positions,
        allP=False,
        delAbove=del_above,
        eps=getattr(self, 'threshold', 1e-3),
        debug=False,
        noOutput=True,
    )
    self.NP = self.NP[~atoms_to_del]
        
    self.NP.positions -= self.NP.get_center_of_mass()

    # --- Update attributes ---
    self.trPlanes_Slicing = all_tr_planes
    self.nAtoms         = len(self.NP)
    self.cog            = self.NP.get_center_of_mass()
    self._flush_stale_data(shape_update="_Sliced")
    self.is_optimized = False
    self.propPostMake(skipSymmetryAnalyzis=self.skipSymmetryAnalyzis,
                      thresholdCoreSurface=self.thresholdCoreSurface,
                      noOutput=False, is_optimized=False)

    if not noOutput:
        print(f"Total number of atoms after truncation = {self.nAtoms}")